<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 3 Multiple regression | Learning Statistical Models Through Simulation in R</title>
<meta name="author" content="Dale J. Barr">
<meta name="description" content="General model for single-level data with \(m\) predictors: \[ Y_i = \beta_0 + \beta_1 X_{1i} + \beta_2 X_{2i} + \ldots + \beta_m X_{mi} + e_i \] The individual \(X_{hi}\) variables can be any...">
<meta name="generator" content="bookdown 0.23 with bs4_book()">
<meta property="og:title" content="Chapter 3 Multiple regression | Learning Statistical Models Through Simulation in R">
<meta property="og:type" content="book">
<meta property="og:url" content="https://psyteachr.github.io/stat-models-v1/multiple-regression.html">
<meta property="og:image" content="https://psyteachr.github.io/stat-models-v1/images/logo.png">
<meta property="og:description" content="General model for single-level data with \(m\) predictors: \[ Y_i = \beta_0 + \beta_1 X_{1i} + \beta_2 X_{2i} + \ldots + \beta_m X_{mi} + e_i \] The individual \(X_{hi}\) variables can be any...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 3 Multiple regression | Learning Statistical Models Through Simulation in R">
<meta name="twitter:description" content="General model for single-level data with \(m\) predictors: \[ Y_i = \beta_0 + \beta_1 X_{1i} + \beta_2 X_{2i} + \ldots + \beta_m X_{mi} + e_i \] The individual \(X_{hi}\) variables can be any...">
<meta name="twitter:image" content="https://psyteachr.github.io/stat-models-v1/images/logo.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.2.5.1/tabs.js"></script><script src="libs/bs3compat-0.2.5.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script><script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'G-6NP3MF25W3');
  </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="include/psyteachr.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Learning Statistical Models Through Simulation in R</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Overview</a></li>
<li><a class="" href="introduction.html"><span class="header-section-number">1</span> Introduction</a></li>
<li><a class="" href="understanding-correlation-and-regression-through-bivariate-simulation.html"><span class="header-section-number">2</span> Understanding correlation and regression through bivariate simulation</a></li>
<li><a class="active" href="multiple-regression.html"><span class="header-section-number">3</span> Multiple regression</a></li>
<li><a class="" href="interactions.html"><span class="header-section-number">4</span> Interactions</a></li>
<li><a class="" href="introducing-linear-mixed-effects-models.html"><span class="header-section-number">5</span> Introducing Linear Mixed-Effects Models</a></li>
<li><a class="" href="linear-mixed-effects-models-with-one-random-factor.html"><span class="header-section-number">6</span> Linear mixed-effects models with one random factor</a></li>
<li><a class="" href="linear-mixed-effects-models-with-crossed-random-factors.html"><span class="header-section-number">7</span> Linear mixed-effects models with crossed random factors</a></li>
<li><a class="" href="generalized-linear-mixed-effects-models.html"><span class="header-section-number">8</span> Generalized linear mixed-effects models</a></li>
<li><a class="" href="modeling-ordinal-data.html"><span class="header-section-number">9</span> Modeling Ordinal Data</a></li>
<li class="book-part">Appendix</li>
<li><a class="" href="symbols.html"><span class="header-section-number">A</span> Symbols</a></li>
<li><a class="" href="bibliography.html"><span class="header-section-number">B</span> Bibliography</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="multiple-regression" class="section level1">
<h1>
<span class="header-section-number">3</span> Multiple regression<a class="anchor" aria-label="anchor" href="#multiple-regression"><i class="fas fa-link"></i></a>
</h1>
<p>General model for single-level data with <span class="math inline">\(m\)</span> predictors:</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 X_{1i} + \beta_2 X_{2i} + \ldots + \beta_m X_{mi} + e_i
\]</span></p>
<p>The individual <span class="math inline">\(X_{hi}\)</span> variables can be any combination of continuous and/or categorical predictors, including interactions among variables.</p>
<p>The <span class="math inline">\(\beta\)</span> values are referred to as <strong>regression coefficients</strong>. Each <span class="math inline">\(\beta_h\)</span> is interpreted as the <strong>partial effect of <span class="math inline">\(\beta_h\)</span> holding constant all other predictor variables.</strong> If you have <span class="math inline">\(m\)</span> predictor variables, you have <span class="math inline">\(m+1\)</span> regression coefficients: one for the intercept, and one for each predictor.</p>
<p>Although discussions of multiple regression are common in statistical textbooks, you will rarely be able to apply the exact model above. This is because the above model assumes single-level data, whereas most psychological data is multi-level. However, the fundamentals are the same for both types of datasets, so it is worthwhile learning them for the simpler case first.</p>
<div id="an-example-how-to-get-a-good-grade-in-statistics" class="section level2">
<h2>
<span class="header-section-number">3.1</span> An example: How to get a good grade in statistics<a class="anchor" aria-label="anchor" href="#an-example-how-to-get-a-good-grade-in-statistics"><i class="fas fa-link"></i></a>
</h2>
<p>Let's look at some (made up, but realistic) data to see how we can use multiple regression to answer various study questions. In this hypothetical study, you have a dataset for 100 statistics students, which includes their final course grade (<code>grade</code>), the number of lectures each student attended (<code>lecture</code>, an integer ranging from 0-10), how many times each student clicked to download online materials (<code>nclicks</code>) and each student's grade point average prior to taking the course, <code>GPA</code>, which ranges from 0 (fail) to 4 (highest possible grade).</p>
<div id="data-import-and-visualization" class="section level3">
<h3>
<span class="header-section-number">3.1.1</span> Data import and visualization<a class="anchor" aria-label="anchor" href="#data-import-and-visualization"><i class="fas fa-link"></i></a>
</h3>
<p>Let's load in the data <a href="data/grades.csv" target="_download">grades.csv</a> and have a look.</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/tidymodels/corrr">"corrr"</a></span><span class="op">)</span> <span class="co"># correlation matrices</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="http://tidyverse.tidyverse.org">"tidyverse"</a></span><span class="op">)</span>

<span class="va">grades</span> <span class="op">&lt;-</span> <span class="fu">read_csv</span><span class="op">(</span><span class="st">"data/grades.csv"</span>, col_types <span class="op">=</span> <span class="st">"ddii"</span><span class="op">)</span>

<span class="va">grades</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="right">grade</th>
<th align="right">GPA</th>
<th align="right">lecture</th>
<th align="right">nclicks</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">2.3951389</td>
<td align="right">1.1341088</td>
<td align="right">6</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="right">3.6651591</td>
<td align="right">0.9708817</td>
<td align="right">6</td>
<td align="right">96</td>
</tr>
<tr class="odd">
<td align="right">2.8527501</td>
<td align="right">3.3432350</td>
<td align="right">6</td>
<td align="right">123</td>
</tr>
<tr class="even">
<td align="right">1.3597001</td>
<td align="right">2.7595763</td>
<td align="right">9</td>
<td align="right">99</td>
</tr>
<tr class="odd">
<td align="right">2.3133351</td>
<td align="right">1.0222222</td>
<td align="right">4</td>
<td align="right">66</td>
</tr>
<tr class="even">
<td align="right">2.5828588</td>
<td align="right">0.8413324</td>
<td align="right">8</td>
<td align="right">99</td>
</tr>
<tr class="odd">
<td align="right">2.6946280</td>
<td align="right">4.0000000</td>
<td align="right">5</td>
<td align="right">86</td>
</tr>
<tr class="even">
<td align="right">3.0549095</td>
<td align="right">2.2949328</td>
<td align="right">7</td>
<td align="right">118</td>
</tr>
<tr class="odd">
<td align="right">3.2104521</td>
<td align="right">3.3874844</td>
<td align="right">9</td>
<td align="right">98</td>
</tr>
<tr class="even">
<td align="right">2.2441902</td>
<td align="right">3.2666345</td>
<td align="right">10</td>
<td align="right">115</td>
</tr>
<tr class="odd">
<td align="right">3.1338540</td>
<td align="right">2.2291875</td>
<td align="right">6</td>
<td align="right">114</td>
</tr>
<tr class="even">
<td align="right">2.2259639</td>
<td align="right">1.7315937</td>
<td align="right">5</td>
<td align="right">84</td>
</tr>
<tr class="odd">
<td align="right">0.0000000</td>
<td align="right">0.4728941</td>
<td align="right">3</td>
<td align="right">95</td>
</tr>
<tr class="even">
<td align="right">3.6278825</td>
<td align="right">1.5600287</td>
<td align="right">10</td>
<td align="right">123</td>
</tr>
<tr class="odd">
<td align="right">1.3405646</td>
<td align="right">2.7518845</td>
<td align="right">9</td>
<td align="right">115</td>
</tr>
<tr class="even">
<td align="right">2.0876289</td>
<td align="right">2.0010052</td>
<td align="right">5</td>
<td align="right">101</td>
</tr>
<tr class="odd">
<td align="right">0.4346968</td>
<td align="right">2.1971687</td>
<td align="right">5</td>
<td align="right">84</td>
</tr>
<tr class="even">
<td align="right">2.2624223</td>
<td align="right">2.7121565</td>
<td align="right">7</td>
<td align="right">90</td>
</tr>
<tr class="odd">
<td align="right">0.7232609</td>
<td align="right">2.8904362</td>
<td align="right">5</td>
<td align="right">83</td>
</tr>
<tr class="even">
<td align="right">3.3532095</td>
<td align="right">1.8096567</td>
<td align="right">8</td>
<td align="right">102</td>
</tr>
<tr class="odd">
<td align="right">3.8653284</td>
<td align="right">3.5056229</td>
<td align="right">8</td>
<td align="right">121</td>
</tr>
<tr class="even">
<td align="right">2.7834847</td>
<td align="right">1.9056691</td>
<td align="right">2</td>
<td align="right">85</td>
</tr>
<tr class="odd">
<td align="right">3.7018629</td>
<td align="right">2.4818014</td>
<td align="right">10</td>
<td align="right">87</td>
</tr>
<tr class="even">
<td align="right">2.4481796</td>
<td align="right">2.4502653</td>
<td align="right">7</td>
<td align="right">81</td>
</tr>
<tr class="odd">
<td align="right">2.7484218</td>
<td align="right">3.7482459</td>
<td align="right">8</td>
<td align="right">110</td>
</tr>
<tr class="even">
<td align="right">1.5854671</td>
<td align="right">2.9709662</td>
<td align="right">9</td>
<td align="right">100</td>
</tr>
<tr class="odd">
<td align="right">2.4482854</td>
<td align="right">2.9100299</td>
<td align="right">10</td>
<td align="right">129</td>
</tr>
<tr class="even">
<td align="right">1.7412862</td>
<td align="right">0.9462394</td>
<td align="right">6</td>
<td align="right">90</td>
</tr>
<tr class="odd">
<td align="right">2.9308757</td>
<td align="right">2.3993738</td>
<td align="right">5</td>
<td align="right">96</td>
</tr>
<tr class="even">
<td align="right">2.8210166</td>
<td align="right">2.4575954</td>
<td align="right">8</td>
<td align="right">129</td>
</tr>
<tr class="odd">
<td align="right">2.5831640</td>
<td align="right">3.0110584</td>
<td align="right">8</td>
<td align="right">118</td>
</tr>
<tr class="even">
<td align="right">0.9659023</td>
<td align="right">1.7466986</td>
<td align="right">7</td>
<td align="right">94</td>
</tr>
<tr class="odd">
<td align="right">2.5080683</td>
<td align="right">3.1387667</td>
<td align="right">6</td>
<td align="right">113</td>
</tr>
<tr class="even">
<td align="right">3.8499634</td>
<td align="right">3.3548881</td>
<td align="right">9</td>
<td align="right">122</td>
</tr>
<tr class="odd">
<td align="right">0.8822343</td>
<td align="right">1.5336613</td>
<td align="right">10</td>
<td align="right">84</td>
</tr>
<tr class="even">
<td align="right">3.9024303</td>
<td align="right">1.7277751</td>
<td align="right">7</td>
<td align="right">82</td>
</tr>
<tr class="odd">
<td align="right">3.4712202</td>
<td align="right">1.7162995</td>
<td align="right">4</td>
<td align="right">83</td>
</tr>
<tr class="even">
<td align="right">2.5115666</td>
<td align="right">2.6390593</td>
<td align="right">6</td>
<td align="right">112</td>
</tr>
<tr class="odd">
<td align="right">3.5146988</td>
<td align="right">3.3294875</td>
<td align="right">7</td>
<td align="right">89</td>
</tr>
<tr class="even">
<td align="right">2.8290397</td>
<td align="right">2.6533664</td>
<td align="right">9</td>
<td align="right">100</td>
</tr>
<tr class="odd">
<td align="right">2.7471315</td>
<td align="right">2.8562607</td>
<td align="right">4</td>
<td align="right">84</td>
</tr>
<tr class="even">
<td align="right">2.7449956</td>
<td align="right">2.9568736</td>
<td align="right">10</td>
<td align="right">102</td>
</tr>
<tr class="odd">
<td align="right">3.0977301</td>
<td align="right">0.3793328</td>
<td align="right">4</td>
<td align="right">111</td>
</tr>
<tr class="even">
<td align="right">2.9783206</td>
<td align="right">2.4891591</td>
<td align="right">6</td>
<td align="right">96</td>
</tr>
<tr class="odd">
<td align="right">2.5125859</td>
<td align="right">2.5350625</td>
<td align="right">9</td>
<td align="right">103</td>
</tr>
<tr class="even">
<td align="right">2.8944945</td>
<td align="right">4.0000000</td>
<td align="right">9</td>
<td align="right">77</td>
</tr>
<tr class="odd">
<td align="right">1.8156094</td>
<td align="right">2.2001745</td>
<td align="right">5</td>
<td align="right">96</td>
</tr>
<tr class="even">
<td align="right">3.0011643</td>
<td align="right">2.8021604</td>
<td align="right">8</td>
<td align="right">112</td>
</tr>
<tr class="odd">
<td align="right">3.8528217</td>
<td align="right">2.8347729</td>
<td align="right">10</td>
<td align="right">76</td>
</tr>
<tr class="even">
<td align="right">2.0496313</td>
<td align="right">1.1178989</td>
<td align="right">6</td>
<td align="right">81</td>
</tr>
<tr class="odd">
<td align="right">2.0300626</td>
<td align="right">1.0270266</td>
<td align="right">3</td>
<td align="right">99</td>
</tr>
<tr class="even">
<td align="right">2.6281108</td>
<td align="right">1.8298851</td>
<td align="right">7</td>
<td align="right">106</td>
</tr>
<tr class="odd">
<td align="right">3.8726751</td>
<td align="right">2.7044881</td>
<td align="right">7</td>
<td align="right">97</td>
</tr>
<tr class="even">
<td align="right">3.5678280</td>
<td align="right">1.6363600</td>
<td align="right">6</td>
<td align="right">85</td>
</tr>
<tr class="odd">
<td align="right">3.7235079</td>
<td align="right">1.6461525</td>
<td align="right">6</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="right">2.5045121</td>
<td align="right">1.9153413</td>
<td align="right">8</td>
<td align="right">92</td>
</tr>
<tr class="odd">
<td align="right">1.2359004</td>
<td align="right">3.4497622</td>
<td align="right">9</td>
<td align="right">122</td>
</tr>
<tr class="even">
<td align="right">2.9946271</td>
<td align="right">2.9535615</td>
<td align="right">7</td>
<td align="right">110</td>
</tr>
<tr class="odd">
<td align="right">2.3944125</td>
<td align="right">3.7537037</td>
<td align="right">6</td>
<td align="right">106</td>
</tr>
<tr class="even">
<td align="right">1.4451098</td>
<td align="right">0.9303599</td>
<td align="right">6</td>
<td align="right">83</td>
</tr>
<tr class="odd">
<td align="right">2.4376733</td>
<td align="right">3.1152237</td>
<td align="right">9</td>
<td align="right">95</td>
</tr>
<tr class="even">
<td align="right">2.1284143</td>
<td align="right">2.3039751</td>
<td align="right">7</td>
<td align="right">119</td>
</tr>
<tr class="odd">
<td align="right">2.8615197</td>
<td align="right">1.7626461</td>
<td align="right">6</td>
<td align="right">99</td>
</tr>
<tr class="even">
<td align="right">2.6672037</td>
<td align="right">1.5447171</td>
<td align="right">4</td>
<td align="right">54</td>
</tr>
<tr class="odd">
<td align="right">1.9934927</td>
<td align="right">1.3665324</td>
<td align="right">5</td>
<td align="right">116</td>
</tr>
<tr class="even">
<td align="right">2.7596577</td>
<td align="right">2.2032136</td>
<td align="right">7</td>
<td align="right">61</td>
</tr>
<tr class="odd">
<td align="right">3.6984273</td>
<td align="right">1.1520123</td>
<td align="right">7</td>
<td align="right">103</td>
</tr>
<tr class="even">
<td align="right">0.9500710</td>
<td align="right">2.1250378</td>
<td align="right">8</td>
<td align="right">96</td>
</tr>
<tr class="odd">
<td align="right">2.5592971</td>
<td align="right">3.7351342</td>
<td align="right">9</td>
<td align="right">80</td>
</tr>
<tr class="even">
<td align="right">3.2861875</td>
<td align="right">3.4664206</td>
<td align="right">10</td>
<td align="right">115</td>
</tr>
<tr class="odd">
<td align="right">2.1222741</td>
<td align="right">3.3947098</td>
<td align="right">8</td>
<td align="right">106</td>
</tr>
<tr class="even">
<td align="right">2.5400241</td>
<td align="right">1.8211989</td>
<td align="right">7</td>
<td align="right">84</td>
</tr>
<tr class="odd">
<td align="right">4.0000000</td>
<td align="right">2.4929632</td>
<td align="right">10</td>
<td align="right">127</td>
</tr>
<tr class="even">
<td align="right">1.4398139</td>
<td align="right">2.6862850</td>
<td align="right">3</td>
<td align="right">109</td>
</tr>
<tr class="odd">
<td align="right">2.4110543</td>
<td align="right">1.4900472</td>
<td align="right">3</td>
<td align="right">92</td>
</tr>
<tr class="even">
<td align="right">0.0000000</td>
<td align="right">0.4014776</td>
<td align="right">3</td>
<td align="right">67</td>
</tr>
<tr class="odd">
<td align="right">2.5738293</td>
<td align="right">2.9524421</td>
<td align="right">6</td>
<td align="right">105</td>
</tr>
<tr class="even">
<td align="right">3.1142057</td>
<td align="right">1.8539501</td>
<td align="right">3</td>
<td align="right">79</td>
</tr>
<tr class="odd">
<td align="right">2.1363495</td>
<td align="right">2.6226571</td>
<td align="right">10</td>
<td align="right">106</td>
</tr>
<tr class="even">
<td align="right">2.6817641</td>
<td align="right">2.2073880</td>
<td align="right">8</td>
<td align="right">110</td>
</tr>
<tr class="odd">
<td align="right">3.3349288</td>
<td align="right">1.7543494</td>
<td align="right">9</td>
<td align="right">105</td>
</tr>
<tr class="even">
<td align="right">1.6988012</td>
<td align="right">2.1246531</td>
<td align="right">4</td>
<td align="right">101</td>
</tr>
<tr class="odd">
<td align="right">1.5526163</td>
<td align="right">1.5286636</td>
<td align="right">10</td>
<td align="right">109</td>
</tr>
<tr class="even">
<td align="right">2.8019608</td>
<td align="right">2.8027352</td>
<td align="right">7</td>
<td align="right">102</td>
</tr>
<tr class="odd">
<td align="right">3.3707676</td>
<td align="right">1.6986526</td>
<td align="right">7</td>
<td align="right">105</td>
</tr>
<tr class="even">
<td align="right">2.2348459</td>
<td align="right">1.4769582</td>
<td align="right">7</td>
<td align="right">80</td>
</tr>
<tr class="odd">
<td align="right">3.6601457</td>
<td align="right">4.0000000</td>
<td align="right">8</td>
<td align="right">109</td>
</tr>
<tr class="even">
<td align="right">2.7328271</td>
<td align="right">3.0817157</td>
<td align="right">10</td>
<td align="right">94</td>
</tr>
<tr class="odd">
<td align="right">2.2687056</td>
<td align="right">3.1470495</td>
<td align="right">6</td>
<td align="right">106</td>
</tr>
<tr class="even">
<td align="right">3.9933377</td>
<td align="right">2.2272781</td>
<td align="right">7</td>
<td align="right">105</td>
</tr>
<tr class="odd">
<td align="right">2.9514553</td>
<td align="right">2.8082666</td>
<td align="right">8</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="right">3.7680715</td>
<td align="right">3.8783317</td>
<td align="right">7</td>
<td align="right">120</td>
</tr>
<tr class="odd">
<td align="right">3.2473376</td>
<td align="right">2.0760349</td>
<td align="right">5</td>
<td align="right">67</td>
</tr>
<tr class="even">
<td align="right">1.7682800</td>
<td align="right">3.3295325</td>
<td align="right">6</td>
<td align="right">84</td>
</tr>
<tr class="odd">
<td align="right">2.8944518</td>
<td align="right">4.0000000</td>
<td align="right">9</td>
<td align="right">102</td>
</tr>
<tr class="even">
<td align="right">4.0000000</td>
<td align="right">4.0000000</td>
<td align="right">9</td>
<td align="right">84</td>
</tr>
<tr class="odd">
<td align="right">2.7733935</td>
<td align="right">3.5680159</td>
<td align="right">7</td>
<td align="right">107</td>
</tr>
<tr class="even">
<td align="right">1.6120128</td>
<td align="right">2.3200362</td>
<td align="right">8</td>
<td align="right">94</td>
</tr>
<tr class="odd">
<td align="right">3.5397356</td>
<td align="right">2.8607765</td>
<td align="right">7</td>
<td align="right">108</td>
</tr>
<tr class="even">
<td align="right">3.5275687</td>
<td align="right">2.8646434</td>
<td align="right">10</td>
<td align="right">109</td>
</tr>
</tbody>
</table></div>
</div>
<p>First let's look at all the pairwise correlations.</p>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">grades</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/correlate.html">correlate</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/shave.html">shave</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/fashion.html">fashion</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Correlation method: 'pearson'
## Missing treated using: 'pairwise.complete.obs'</code></pre>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">term</th>
<th align="left">grade</th>
<th align="left">GPA</th>
<th align="left">lecture</th>
<th align="left">nclicks</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">grade</td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">GPA</td>
<td align="left">.25</td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">lecture</td>
<td align="left">.24</td>
<td align="left">.44</td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">nclicks</td>
<td align="left">.16</td>
<td align="left">.30</td>
<td align="left">.36</td>
<td align="left"></td>
</tr>
</tbody>
</table></div>
</div>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/pairs.html">pairs</a></span><span class="op">(</span><span class="va">grades</span><span class="op">)</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:pairs"></span>
<img src="03-multiple-regression_files/figure-html/pairs-1.png" alt="All pairwise relationships in the `grades` dataset." width="100%"><p class="caption">
Figure 2.2: All pairwise relationships in the <code>grades</code> dataset.
</p>
</div>
</div>
<div id="estimation-and-interpretation" class="section level3">
<h3>
<span class="header-section-number">3.1.2</span> Estimation and interpretation<a class="anchor" aria-label="anchor" href="#estimation-and-interpretation"><i class="fas fa-link"></i></a>
</h3>
<p>To estimate the regression coefficients (the <span class="math inline">\(\beta\)</span>s), we will use the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function. For a GLM with <span class="math inline">\(m\)</span> predictors:</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 X_{1i} + \beta_2 X_{2i} + \ldots + \beta_m X_{mi} + e_i
\]</span></p>
<p>The call to base R's <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> is</p>
<p><code><a href="https://rdrr.io/r/stats/lm.html">lm(Y ~ X1 + X2 + ... + Xm, data)</a></code></p>
<p>The <code>Y</code> variable is your response variable, and the <code>X</code> variables are the predictor variables. Note that you don't need to explicitly specify the intercept or residual terms; those are included by default.</p>
<p>For the current data, let's predict <code>grade</code> from <code>lecture</code> and <code>nclicks</code>.</p>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">my_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">grade</span> <span class="op">~</span> <span class="va">lecture</span> <span class="op">+</span> <span class="va">nclicks</span>, <span class="va">grades</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">my_model</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = grade ~ lecture + nclicks, data = grades)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.21653 -0.40603  0.02267  0.60720  1.38558 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept) 1.462037   0.571124   2.560   0.0120 *
## lecture     0.091501   0.045766   1.999   0.0484 *
## nclicks     0.005052   0.006051   0.835   0.4058  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.8692 on 97 degrees of freedom
## Multiple R-squared:  0.06543,    Adjusted R-squared:  0.04616 
## F-statistic: 3.395 on 2 and 97 DF,  p-value: 0.03756</code></pre>
<p>We'll often write the parameter symbol with a little hat on top to make clear that we are dealing with estimates from the sample rather than the (unknown) true population values. From above:</p>
<ul>
<li>
<span class="math inline">\(\hat{\beta}_0\)</span> = 1.46</li>
<li>
<span class="math inline">\(\hat{\beta}_1\)</span> = 0.09</li>
<li>
<span class="math inline">\(\hat{\beta}_2\)</span> = 0.01</li>
</ul>
<p>This tells us that a person's predicted grade is related to their lecture attendance and download rate by the following formula:</p>
<p><code>grade</code> = 1.46 + 0.09 <span class="math inline">\(\times\)</span> <code>lecture</code> + 0.01 <span class="math inline">\(\times\)</span> <code>nclicks</code></p>
<p>Because <span class="math inline">\(\hat{\beta}_1\)</span> and <span class="math inline">\(\hat{\beta}_2\)</span> are both positive, we know that higher values of <code>lecture</code> and <code>nclicks</code> are associated with higher grades.</p>
<p>So if you were asked, what grade would you predict for a student who attends 3 lectures and downloaded 70 times, you could easily figure that out by substituting the appropriate values.</p>
<p><code>grade</code> = 1.46 + 0.09 <span class="math inline">\(\times\)</span> 3 + 0.01 <span class="math inline">\(\times\)</span> 70</p>
<p>which equals</p>
<p><code>grade</code> = 1.46 + 0.27 + 0.7</p>
<p>and reduces to</p>
<p><code>grade</code> = 2.43</p>
</div>
<div id="predictions-from-the-linear-model-using-predict" class="section level3">
<h3>
<span class="header-section-number">3.1.3</span> Predictions from the linear model using <code>predict()</code><a class="anchor" aria-label="anchor" href="#predictions-from-the-linear-model-using-predict"><i class="fas fa-link"></i></a>
</h3>
<p>If we want to predict response values for new predictor values, we can use the <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> function in base R.</p>
<p><code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> takes two main arguments. The first argument is a fitted model object (i.e., <code>my_model</code> from above) and the second is a data frame (or tibble) containing new values for the predictors.</p>
<div class="warning">
<p>
You need to include <strong>all</strong> of the predictor variables in the new table. You'll get an error message if your tibble is missing any predictors. You also need to make sure that the variable names in the new table <strong>exactly</strong> match the variable names in the model.
</p>
</div>
<p>Let's create a tibble with new values and try it out.</p>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## a 'tribble' is a way to make a tibble by rows,</span>
<span class="co">## rather than by columns. This is sometimes useful</span>
<span class="va">new_data</span> <span class="op">&lt;-</span> <span class="fu">tribble</span><span class="op">(</span><span class="op">~</span><span class="va">lecture</span>, <span class="op">~</span><span class="va">nclicks</span>,
                    <span class="fl">3</span>, <span class="fl">70</span>,
                    <span class="fl">10</span>, <span class="fl">130</span>,
                    <span class="fl">0</span>, <span class="fl">20</span>,
                    <span class="fl">5</span>, <span class="fl">100</span><span class="op">)</span></code></pre></div>
<div class="info">
<p>The <code>tribble()</code> function provides a way to build a tibble row by row, whereas with <code>tibble()</code> the table is built column by column.</p>
<p>The first row of the <code>tribble()</code> contains the column names, each preceded by a tilde (<code><a href="https://rdrr.io/r/base/tilde.html">~</a></code>).</p>
<p>This is sometimes easier to read than doing it row by row, although the result is the same. Consider that we could have made the above table using</p>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">new_data</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>lecture <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">10</span>, <span class="fl">0</span>, <span class="fl">5</span><span class="op">)</span>,
                   nclicks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">70</span>, <span class="fl">130</span>, <span class="fl">20</span>, <span class="fl">100</span><span class="op">)</span><span class="op">)</span></code></pre></div>
</div>
<p>Now that we've created our table <code>new_data</code>, we just pass it to <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> and it will return a vector with the predictions for <span class="math inline">\(Y\)</span> (<code>grade</code>).</p>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">my_model</span>, <span class="va">new_data</span><span class="op">)</span></code></pre></div>
<pre><code>##        1        2        3        4 
## 2.090214 3.033869 1.563087 2.424790</code></pre>
<p>That's great, but maybe we want to line it up with the predictor values. We can do this by just adding it as a new column to <code>new_data</code>.</p>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">new_data</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>predicted_grade <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">my_model</span>, <span class="va">new_data</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="right">lecture</th>
<th align="right">nclicks</th>
<th align="right">predicted_grade</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">3</td>
<td align="right">70</td>
<td align="right">2.090214</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">130</td>
<td align="right">3.033869</td>
</tr>
<tr class="odd">
<td align="right">0</td>
<td align="right">20</td>
<td align="right">1.563087</td>
</tr>
<tr class="even">
<td align="right">5</td>
<td align="right">100</td>
<td align="right">2.424790</td>
</tr>
</tbody>
</table></div>
</div>
<p>Want to see more options for <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code>? Check the help at <code><a href="https://rdrr.io/r/stats/predict.lm.html">?predict.lm</a></code>.</p>
</div>
<div id="visualizing-partial-effects" class="section level3">
<h3>
<span class="header-section-number">3.1.4</span> Visualizing partial effects<a class="anchor" aria-label="anchor" href="#visualizing-partial-effects"><i class="fas fa-link"></i></a>
</h3>
<p>As noted above the parameter estimates for each regression coefficient tell us about the <strong>partial</strong> effect of that variable; it's effect holding all of the others constant. Is there a way to visualize this partial effect? Yes, you can do this using the <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> function, by making a table with varying values for the focal predictor, while filling in all of the other predictors with their mean values.</p>
<p>For example, let's visualize the partial effect of <code>lecture</code> on <code>grade</code> holding <code>nclicks</code> constant at its mean value.</p>
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">nclicks_mean</span> <span class="op">&lt;-</span> <span class="va">grades</span> <span class="op">%&gt;%</span> <span class="fu">pull</span><span class="op">(</span><span class="va">nclicks</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="op">)</span>

<span class="co">## new data for prediction</span>
<span class="va">new_lecture</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>lecture <span class="op">=</span> <span class="fl">0</span><span class="op">:</span><span class="fl">10</span>,
                      nclicks <span class="op">=</span> <span class="va">nclicks_mean</span><span class="op">)</span>

<span class="co">## add the predicted value to new_lecture</span>
<span class="va">new_lecture2</span> <span class="op">&lt;-</span> <span class="va">new_lecture</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>grade <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">my_model</span>, <span class="va">new_lecture</span><span class="op">)</span><span class="op">)</span>

<span class="va">new_lecture2</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="right">lecture</th>
<th align="right">nclicks</th>
<th align="right">grade</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="right">98.32</td>
<td align="right">1.958798</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">98.32</td>
<td align="right">2.050299</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="right">98.32</td>
<td align="right">2.141799</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="right">98.32</td>
<td align="right">2.233300</td>
</tr>
<tr class="odd">
<td align="right">4</td>
<td align="right">98.32</td>
<td align="right">2.324801</td>
</tr>
<tr class="even">
<td align="right">5</td>
<td align="right">98.32</td>
<td align="right">2.416302</td>
</tr>
<tr class="odd">
<td align="right">6</td>
<td align="right">98.32</td>
<td align="right">2.507803</td>
</tr>
<tr class="even">
<td align="right">7</td>
<td align="right">98.32</td>
<td align="right">2.599303</td>
</tr>
<tr class="odd">
<td align="right">8</td>
<td align="right">98.32</td>
<td align="right">2.690804</td>
</tr>
<tr class="even">
<td align="right">9</td>
<td align="right">98.32</td>
<td align="right">2.782305</td>
</tr>
<tr class="odd">
<td align="right">10</td>
<td align="right">98.32</td>
<td align="right">2.873806</td>
</tr>
</tbody>
</table></div>
</div>
<p>Now let's plot.</p>
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="va">grades</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">lecture</span>, <span class="va">grade</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_line</span><span class="op">(</span>data <span class="op">=</span> <span class="va">new_lecture2</span><span class="op">)</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:partial-lecture-plot"></span>
<img src="03-multiple-regression_files/figure-html/partial-lecture-plot-1.png" alt="Partial effect of 'lecture' on grade, with nclicks at its mean value." width="100%"><p class="caption">
Figure 3.1: Partial effect of 'lecture' on grade, with nclicks at its mean value.
</p>
</div>
<div class="warning">
<p>Partial effect plots only make sense when there are no interactions in the model between the focal predictor and any other predictor.</p>
<p>The reason is that when there are interactions, the partial effect of focal predictor <span class="math inline">\(X_i\)</span> will differ across the values of the other variables it interacts with.</p>
</div>
<p>Now can you visualize the partial effect of <code>nclicks</code> on <code>grade</code>?</p>
<p>See the solution at the bottom of the page.</p>
</div>
<div id="standardizing-coefficients" class="section level3">
<h3>
<span class="header-section-number">3.1.5</span> Standardizing coefficients<a class="anchor" aria-label="anchor" href="#standardizing-coefficients"><i class="fas fa-link"></i></a>
</h3>
<p>One kind of question that we often use multiple regression to address is, <strong>Which predictors matter most in predicting Y?</strong></p>
<p>Now, you can't just read off the <span class="math inline">\(\hat{\beta}\)</span> values and choose the one with the largest absolute value, because the predictors are all on different scales. To answer this question, you need to <strong>center</strong> and <strong>scale</strong> the predictors.</p>
<p>Remember <span class="math inline">\(z\)</span> scores?</p>
<p><span class="math display">\[
z = \frac{X - \mu_x}{\sigma_x}
\]</span></p>
<p>A <span class="math inline">\(z\)</span> score represents the distance of a score <span class="math inline">\(X\)</span> from the sample mean (<span class="math inline">\(\mu_x\)</span>) in standard deviation units (<span class="math inline">\(\sigma_x\)</span>). So a <span class="math inline">\(z\)</span> score of 1 means that the score is one standard deviation about the mean; a <span class="math inline">\(z\)</span>-score of -2.5 means 2.5 standard deviations below the mean. <span class="math inline">\(Z\)</span>-scores give us a way of comparing things that come from different populations by calibrating them to the standard normal distribution (a distribution with a mean of 0 and a standard deviation of 1).</p>
<p>So we re-scale our predictors by converting them to <span class="math inline">\(z\)</span>-scores. This is easy enough to do.</p>
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">grades2</span> <span class="op">&lt;-</span> <span class="va">grades</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>lecture_c <span class="op">=</span> <span class="op">(</span><span class="va">lecture</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">lecture</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">lecture</span><span class="op">)</span>,
         nclicks_c <span class="op">=</span> <span class="op">(</span><span class="va">nclicks</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">nclicks</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">nclicks</span><span class="op">)</span><span class="op">)</span>

<span class="va">grades2</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="right">grade</th>
<th align="right">GPA</th>
<th align="right">lecture</th>
<th align="right">nclicks</th>
<th align="right">lecture_c</th>
<th align="right">nclicks_c</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">2.3951389</td>
<td align="right">1.1341088</td>
<td align="right">6</td>
<td align="right">88</td>
<td align="right">-0.4835417</td>
<td align="right">-0.6664932</td>
</tr>
<tr class="even">
<td align="right">3.6651591</td>
<td align="right">0.9708817</td>
<td align="right">6</td>
<td align="right">96</td>
<td align="right">-0.4835417</td>
<td align="right">-0.1498318</td>
</tr>
<tr class="odd">
<td align="right">2.8527501</td>
<td align="right">3.3432350</td>
<td align="right">6</td>
<td align="right">123</td>
<td align="right">-0.4835417</td>
<td align="right">1.5939004</td>
</tr>
<tr class="even">
<td align="right">1.3597001</td>
<td align="right">2.7595763</td>
<td align="right">9</td>
<td align="right">99</td>
<td align="right">0.9817363</td>
<td align="right">0.0439162</td>
</tr>
<tr class="odd">
<td align="right">2.3133351</td>
<td align="right">1.0222222</td>
<td align="right">4</td>
<td align="right">66</td>
<td align="right">-1.4603938</td>
<td align="right">-2.0873120</td>
</tr>
<tr class="even">
<td align="right">2.5828588</td>
<td align="right">0.8413324</td>
<td align="right">8</td>
<td align="right">99</td>
<td align="right">0.4933103</td>
<td align="right">0.0439162</td>
</tr>
<tr class="odd">
<td align="right">2.6946280</td>
<td align="right">4.0000000</td>
<td align="right">5</td>
<td align="right">86</td>
<td align="right">-0.9719678</td>
<td align="right">-0.7956586</td>
</tr>
<tr class="even">
<td align="right">3.0549095</td>
<td align="right">2.2949328</td>
<td align="right">7</td>
<td align="right">118</td>
<td align="right">0.0048843</td>
<td align="right">1.2709870</td>
</tr>
<tr class="odd">
<td align="right">3.2104521</td>
<td align="right">3.3874844</td>
<td align="right">9</td>
<td align="right">98</td>
<td align="right">0.9817363</td>
<td align="right">-0.0206665</td>
</tr>
<tr class="even">
<td align="right">2.2441902</td>
<td align="right">3.2666345</td>
<td align="right">10</td>
<td align="right">115</td>
<td align="right">1.4701623</td>
<td align="right">1.0772390</td>
</tr>
<tr class="odd">
<td align="right">3.1338540</td>
<td align="right">2.2291875</td>
<td align="right">6</td>
<td align="right">114</td>
<td align="right">-0.4835417</td>
<td align="right">1.0126563</td>
</tr>
<tr class="even">
<td align="right">2.2259639</td>
<td align="right">1.7315937</td>
<td align="right">5</td>
<td align="right">84</td>
<td align="right">-0.9719678</td>
<td align="right">-0.9248239</td>
</tr>
<tr class="odd">
<td align="right">0.0000000</td>
<td align="right">0.4728941</td>
<td align="right">3</td>
<td align="right">95</td>
<td align="right">-1.9488198</td>
<td align="right">-0.2144145</td>
</tr>
<tr class="even">
<td align="right">3.6278825</td>
<td align="right">1.5600287</td>
<td align="right">10</td>
<td align="right">123</td>
<td align="right">1.4701623</td>
<td align="right">1.5939004</td>
</tr>
<tr class="odd">
<td align="right">1.3405646</td>
<td align="right">2.7518845</td>
<td align="right">9</td>
<td align="right">115</td>
<td align="right">0.9817363</td>
<td align="right">1.0772390</td>
</tr>
<tr class="even">
<td align="right">2.0876289</td>
<td align="right">2.0010052</td>
<td align="right">5</td>
<td align="right">101</td>
<td align="right">-0.9719678</td>
<td align="right">0.1730816</td>
</tr>
<tr class="odd">
<td align="right">0.4346968</td>
<td align="right">2.1971687</td>
<td align="right">5</td>
<td align="right">84</td>
<td align="right">-0.9719678</td>
<td align="right">-0.9248239</td>
</tr>
<tr class="even">
<td align="right">2.2624223</td>
<td align="right">2.7121565</td>
<td align="right">7</td>
<td align="right">90</td>
<td align="right">0.0048843</td>
<td align="right">-0.5373279</td>
</tr>
<tr class="odd">
<td align="right">0.7232609</td>
<td align="right">2.8904362</td>
<td align="right">5</td>
<td align="right">83</td>
<td align="right">-0.9719678</td>
<td align="right">-0.9894066</td>
</tr>
<tr class="even">
<td align="right">3.3532095</td>
<td align="right">1.8096567</td>
<td align="right">8</td>
<td align="right">102</td>
<td align="right">0.4933103</td>
<td align="right">0.2376642</td>
</tr>
<tr class="odd">
<td align="right">3.8653284</td>
<td align="right">3.5056229</td>
<td align="right">8</td>
<td align="right">121</td>
<td align="right">0.4933103</td>
<td align="right">1.4647351</td>
</tr>
<tr class="even">
<td align="right">2.7834847</td>
<td align="right">1.9056691</td>
<td align="right">2</td>
<td align="right">85</td>
<td align="right">-2.4372458</td>
<td align="right">-0.8602412</td>
</tr>
<tr class="odd">
<td align="right">3.7018629</td>
<td align="right">2.4818014</td>
<td align="right">10</td>
<td align="right">87</td>
<td align="right">1.4701623</td>
<td align="right">-0.7310759</td>
</tr>
<tr class="even">
<td align="right">2.4481796</td>
<td align="right">2.4502653</td>
<td align="right">7</td>
<td align="right">81</td>
<td align="right">0.0048843</td>
<td align="right">-1.1185719</td>
</tr>
<tr class="odd">
<td align="right">2.7484218</td>
<td align="right">3.7482459</td>
<td align="right">8</td>
<td align="right">110</td>
<td align="right">0.4933103</td>
<td align="right">0.7543256</td>
</tr>
<tr class="even">
<td align="right">1.5854671</td>
<td align="right">2.9709662</td>
<td align="right">9</td>
<td align="right">100</td>
<td align="right">0.9817363</td>
<td align="right">0.1084989</td>
</tr>
<tr class="odd">
<td align="right">2.4482854</td>
<td align="right">2.9100299</td>
<td align="right">10</td>
<td align="right">129</td>
<td align="right">1.4701623</td>
<td align="right">1.9813965</td>
</tr>
<tr class="even">
<td align="right">1.7412862</td>
<td align="right">0.9462394</td>
<td align="right">6</td>
<td align="right">90</td>
<td align="right">-0.4835417</td>
<td align="right">-0.5373279</td>
</tr>
<tr class="odd">
<td align="right">2.9308757</td>
<td align="right">2.3993738</td>
<td align="right">5</td>
<td align="right">96</td>
<td align="right">-0.9719678</td>
<td align="right">-0.1498318</td>
</tr>
<tr class="even">
<td align="right">2.8210166</td>
<td align="right">2.4575954</td>
<td align="right">8</td>
<td align="right">129</td>
<td align="right">0.4933103</td>
<td align="right">1.9813965</td>
</tr>
<tr class="odd">
<td align="right">2.5831640</td>
<td align="right">3.0110584</td>
<td align="right">8</td>
<td align="right">118</td>
<td align="right">0.4933103</td>
<td align="right">1.2709870</td>
</tr>
<tr class="even">
<td align="right">0.9659023</td>
<td align="right">1.7466986</td>
<td align="right">7</td>
<td align="right">94</td>
<td align="right">0.0048843</td>
<td align="right">-0.2789972</td>
</tr>
<tr class="odd">
<td align="right">2.5080683</td>
<td align="right">3.1387667</td>
<td align="right">6</td>
<td align="right">113</td>
<td align="right">-0.4835417</td>
<td align="right">0.9480737</td>
</tr>
<tr class="even">
<td align="right">3.8499634</td>
<td align="right">3.3548881</td>
<td align="right">9</td>
<td align="right">122</td>
<td align="right">0.9817363</td>
<td align="right">1.5293177</td>
</tr>
<tr class="odd">
<td align="right">0.8822343</td>
<td align="right">1.5336613</td>
<td align="right">10</td>
<td align="right">84</td>
<td align="right">1.4701623</td>
<td align="right">-0.9248239</td>
</tr>
<tr class="even">
<td align="right">3.9024303</td>
<td align="right">1.7277751</td>
<td align="right">7</td>
<td align="right">82</td>
<td align="right">0.0048843</td>
<td align="right">-1.0539892</td>
</tr>
<tr class="odd">
<td align="right">3.4712202</td>
<td align="right">1.7162995</td>
<td align="right">4</td>
<td align="right">83</td>
<td align="right">-1.4603938</td>
<td align="right">-0.9894066</td>
</tr>
<tr class="even">
<td align="right">2.5115666</td>
<td align="right">2.6390593</td>
<td align="right">6</td>
<td align="right">112</td>
<td align="right">-0.4835417</td>
<td align="right">0.8834910</td>
</tr>
<tr class="odd">
<td align="right">3.5146988</td>
<td align="right">3.3294875</td>
<td align="right">7</td>
<td align="right">89</td>
<td align="right">0.0048843</td>
<td align="right">-0.6019105</td>
</tr>
<tr class="even">
<td align="right">2.8290397</td>
<td align="right">2.6533664</td>
<td align="right">9</td>
<td align="right">100</td>
<td align="right">0.9817363</td>
<td align="right">0.1084989</td>
</tr>
<tr class="odd">
<td align="right">2.7471315</td>
<td align="right">2.8562607</td>
<td align="right">4</td>
<td align="right">84</td>
<td align="right">-1.4603938</td>
<td align="right">-0.9248239</td>
</tr>
<tr class="even">
<td align="right">2.7449956</td>
<td align="right">2.9568736</td>
<td align="right">10</td>
<td align="right">102</td>
<td align="right">1.4701623</td>
<td align="right">0.2376642</td>
</tr>
<tr class="odd">
<td align="right">3.0977301</td>
<td align="right">0.3793328</td>
<td align="right">4</td>
<td align="right">111</td>
<td align="right">-1.4603938</td>
<td align="right">0.8189083</td>
</tr>
<tr class="even">
<td align="right">2.9783206</td>
<td align="right">2.4891591</td>
<td align="right">6</td>
<td align="right">96</td>
<td align="right">-0.4835417</td>
<td align="right">-0.1498318</td>
</tr>
<tr class="odd">
<td align="right">2.5125859</td>
<td align="right">2.5350625</td>
<td align="right">9</td>
<td align="right">103</td>
<td align="right">0.9817363</td>
<td align="right">0.3022469</td>
</tr>
<tr class="even">
<td align="right">2.8944945</td>
<td align="right">4.0000000</td>
<td align="right">9</td>
<td align="right">77</td>
<td align="right">0.9817363</td>
<td align="right">-1.3769026</td>
</tr>
<tr class="odd">
<td align="right">1.8156094</td>
<td align="right">2.2001745</td>
<td align="right">5</td>
<td align="right">96</td>
<td align="right">-0.9719678</td>
<td align="right">-0.1498318</td>
</tr>
<tr class="even">
<td align="right">3.0011643</td>
<td align="right">2.8021604</td>
<td align="right">8</td>
<td align="right">112</td>
<td align="right">0.4933103</td>
<td align="right">0.8834910</td>
</tr>
<tr class="odd">
<td align="right">3.8528217</td>
<td align="right">2.8347729</td>
<td align="right">10</td>
<td align="right">76</td>
<td align="right">1.4701623</td>
<td align="right">-1.4414853</td>
</tr>
<tr class="even">
<td align="right">2.0496313</td>
<td align="right">1.1178989</td>
<td align="right">6</td>
<td align="right">81</td>
<td align="right">-0.4835417</td>
<td align="right">-1.1185719</td>
</tr>
<tr class="odd">
<td align="right">2.0300626</td>
<td align="right">1.0270266</td>
<td align="right">3</td>
<td align="right">99</td>
<td align="right">-1.9488198</td>
<td align="right">0.0439162</td>
</tr>
<tr class="even">
<td align="right">2.6281108</td>
<td align="right">1.8298851</td>
<td align="right">7</td>
<td align="right">106</td>
<td align="right">0.0048843</td>
<td align="right">0.4959949</td>
</tr>
<tr class="odd">
<td align="right">3.8726751</td>
<td align="right">2.7044881</td>
<td align="right">7</td>
<td align="right">97</td>
<td align="right">0.0048843</td>
<td align="right">-0.0852491</td>
</tr>
<tr class="even">
<td align="right">3.5678280</td>
<td align="right">1.6363600</td>
<td align="right">6</td>
<td align="right">85</td>
<td align="right">-0.4835417</td>
<td align="right">-0.8602412</td>
</tr>
<tr class="odd">
<td align="right">3.7235079</td>
<td align="right">1.6461525</td>
<td align="right">6</td>
<td align="right">88</td>
<td align="right">-0.4835417</td>
<td align="right">-0.6664932</td>
</tr>
<tr class="even">
<td align="right">2.5045121</td>
<td align="right">1.9153413</td>
<td align="right">8</td>
<td align="right">92</td>
<td align="right">0.4933103</td>
<td align="right">-0.4081625</td>
</tr>
<tr class="odd">
<td align="right">1.2359004</td>
<td align="right">3.4497622</td>
<td align="right">9</td>
<td align="right">122</td>
<td align="right">0.9817363</td>
<td align="right">1.5293177</td>
</tr>
<tr class="even">
<td align="right">2.9946271</td>
<td align="right">2.9535615</td>
<td align="right">7</td>
<td align="right">110</td>
<td align="right">0.0048843</td>
<td align="right">0.7543256</td>
</tr>
<tr class="odd">
<td align="right">2.3944125</td>
<td align="right">3.7537037</td>
<td align="right">6</td>
<td align="right">106</td>
<td align="right">-0.4835417</td>
<td align="right">0.4959949</td>
</tr>
<tr class="even">
<td align="right">1.4451098</td>
<td align="right">0.9303599</td>
<td align="right">6</td>
<td align="right">83</td>
<td align="right">-0.4835417</td>
<td align="right">-0.9894066</td>
</tr>
<tr class="odd">
<td align="right">2.4376733</td>
<td align="right">3.1152237</td>
<td align="right">9</td>
<td align="right">95</td>
<td align="right">0.9817363</td>
<td align="right">-0.2144145</td>
</tr>
<tr class="even">
<td align="right">2.1284143</td>
<td align="right">2.3039751</td>
<td align="right">7</td>
<td align="right">119</td>
<td align="right">0.0048843</td>
<td align="right">1.3355697</td>
</tr>
<tr class="odd">
<td align="right">2.8615197</td>
<td align="right">1.7626461</td>
<td align="right">6</td>
<td align="right">99</td>
<td align="right">-0.4835417</td>
<td align="right">0.0439162</td>
</tr>
<tr class="even">
<td align="right">2.6672037</td>
<td align="right">1.5447171</td>
<td align="right">4</td>
<td align="right">54</td>
<td align="right">-1.4603938</td>
<td align="right">-2.8623041</td>
</tr>
<tr class="odd">
<td align="right">1.9934927</td>
<td align="right">1.3665324</td>
<td align="right">5</td>
<td align="right">116</td>
<td align="right">-0.9719678</td>
<td align="right">1.1418217</td>
</tr>
<tr class="even">
<td align="right">2.7596577</td>
<td align="right">2.2032136</td>
<td align="right">7</td>
<td align="right">61</td>
<td align="right">0.0048843</td>
<td align="right">-2.4102254</td>
</tr>
<tr class="odd">
<td align="right">3.6984273</td>
<td align="right">1.1520123</td>
<td align="right">7</td>
<td align="right">103</td>
<td align="right">0.0048843</td>
<td align="right">0.3022469</td>
</tr>
<tr class="even">
<td align="right">0.9500710</td>
<td align="right">2.1250378</td>
<td align="right">8</td>
<td align="right">96</td>
<td align="right">0.4933103</td>
<td align="right">-0.1498318</td>
</tr>
<tr class="odd">
<td align="right">2.5592971</td>
<td align="right">3.7351342</td>
<td align="right">9</td>
<td align="right">80</td>
<td align="right">0.9817363</td>
<td align="right">-1.1831546</td>
</tr>
<tr class="even">
<td align="right">3.2861875</td>
<td align="right">3.4664206</td>
<td align="right">10</td>
<td align="right">115</td>
<td align="right">1.4701623</td>
<td align="right">1.0772390</td>
</tr>
<tr class="odd">
<td align="right">2.1222741</td>
<td align="right">3.3947098</td>
<td align="right">8</td>
<td align="right">106</td>
<td align="right">0.4933103</td>
<td align="right">0.4959949</td>
</tr>
<tr class="even">
<td align="right">2.5400241</td>
<td align="right">1.8211989</td>
<td align="right">7</td>
<td align="right">84</td>
<td align="right">0.0048843</td>
<td align="right">-0.9248239</td>
</tr>
<tr class="odd">
<td align="right">4.0000000</td>
<td align="right">2.4929632</td>
<td align="right">10</td>
<td align="right">127</td>
<td align="right">1.4701623</td>
<td align="right">1.8522311</td>
</tr>
<tr class="even">
<td align="right">1.4398139</td>
<td align="right">2.6862850</td>
<td align="right">3</td>
<td align="right">109</td>
<td align="right">-1.9488198</td>
<td align="right">0.6897430</td>
</tr>
<tr class="odd">
<td align="right">2.4110543</td>
<td align="right">1.4900472</td>
<td align="right">3</td>
<td align="right">92</td>
<td align="right">-1.9488198</td>
<td align="right">-0.4081625</td>
</tr>
<tr class="even">
<td align="right">0.0000000</td>
<td align="right">0.4014776</td>
<td align="right">3</td>
<td align="right">67</td>
<td align="right">-1.9488198</td>
<td align="right">-2.0227294</td>
</tr>
<tr class="odd">
<td align="right">2.5738293</td>
<td align="right">2.9524421</td>
<td align="right">6</td>
<td align="right">105</td>
<td align="right">-0.4835417</td>
<td align="right">0.4314123</td>
</tr>
<tr class="even">
<td align="right">3.1142057</td>
<td align="right">1.8539501</td>
<td align="right">3</td>
<td align="right">79</td>
<td align="right">-1.9488198</td>
<td align="right">-1.2477373</td>
</tr>
<tr class="odd">
<td align="right">2.1363495</td>
<td align="right">2.6226571</td>
<td align="right">10</td>
<td align="right">106</td>
<td align="right">1.4701623</td>
<td align="right">0.4959949</td>
</tr>
<tr class="even">
<td align="right">2.6817641</td>
<td align="right">2.2073880</td>
<td align="right">8</td>
<td align="right">110</td>
<td align="right">0.4933103</td>
<td align="right">0.7543256</td>
</tr>
<tr class="odd">
<td align="right">3.3349288</td>
<td align="right">1.7543494</td>
<td align="right">9</td>
<td align="right">105</td>
<td align="right">0.9817363</td>
<td align="right">0.4314123</td>
</tr>
<tr class="even">
<td align="right">1.6988012</td>
<td align="right">2.1246531</td>
<td align="right">4</td>
<td align="right">101</td>
<td align="right">-1.4603938</td>
<td align="right">0.1730816</td>
</tr>
<tr class="odd">
<td align="right">1.5526163</td>
<td align="right">1.5286636</td>
<td align="right">10</td>
<td align="right">109</td>
<td align="right">1.4701623</td>
<td align="right">0.6897430</td>
</tr>
<tr class="even">
<td align="right">2.8019608</td>
<td align="right">2.8027352</td>
<td align="right">7</td>
<td align="right">102</td>
<td align="right">0.0048843</td>
<td align="right">0.2376642</td>
</tr>
<tr class="odd">
<td align="right">3.3707676</td>
<td align="right">1.6986526</td>
<td align="right">7</td>
<td align="right">105</td>
<td align="right">0.0048843</td>
<td align="right">0.4314123</td>
</tr>
<tr class="even">
<td align="right">2.2348459</td>
<td align="right">1.4769582</td>
<td align="right">7</td>
<td align="right">80</td>
<td align="right">0.0048843</td>
<td align="right">-1.1831546</td>
</tr>
<tr class="odd">
<td align="right">3.6601457</td>
<td align="right">4.0000000</td>
<td align="right">8</td>
<td align="right">109</td>
<td align="right">0.4933103</td>
<td align="right">0.6897430</td>
</tr>
<tr class="even">
<td align="right">2.7328271</td>
<td align="right">3.0817157</td>
<td align="right">10</td>
<td align="right">94</td>
<td align="right">1.4701623</td>
<td align="right">-0.2789972</td>
</tr>
<tr class="odd">
<td align="right">2.2687056</td>
<td align="right">3.1470495</td>
<td align="right">6</td>
<td align="right">106</td>
<td align="right">-0.4835417</td>
<td align="right">0.4959949</td>
</tr>
<tr class="even">
<td align="right">3.9933377</td>
<td align="right">2.2272781</td>
<td align="right">7</td>
<td align="right">105</td>
<td align="right">0.0048843</td>
<td align="right">0.4314123</td>
</tr>
<tr class="odd">
<td align="right">2.9514553</td>
<td align="right">2.8082666</td>
<td align="right">8</td>
<td align="right">88</td>
<td align="right">0.4933103</td>
<td align="right">-0.6664932</td>
</tr>
<tr class="even">
<td align="right">3.7680715</td>
<td align="right">3.8783317</td>
<td align="right">7</td>
<td align="right">120</td>
<td align="right">0.0048843</td>
<td align="right">1.4001524</td>
</tr>
<tr class="odd">
<td align="right">3.2473376</td>
<td align="right">2.0760349</td>
<td align="right">5</td>
<td align="right">67</td>
<td align="right">-0.9719678</td>
<td align="right">-2.0227294</td>
</tr>
<tr class="even">
<td align="right">1.7682800</td>
<td align="right">3.3295325</td>
<td align="right">6</td>
<td align="right">84</td>
<td align="right">-0.4835417</td>
<td align="right">-0.9248239</td>
</tr>
<tr class="odd">
<td align="right">2.8944518</td>
<td align="right">4.0000000</td>
<td align="right">9</td>
<td align="right">102</td>
<td align="right">0.9817363</td>
<td align="right">0.2376642</td>
</tr>
<tr class="even">
<td align="right">4.0000000</td>
<td align="right">4.0000000</td>
<td align="right">9</td>
<td align="right">84</td>
<td align="right">0.9817363</td>
<td align="right">-0.9248239</td>
</tr>
<tr class="odd">
<td align="right">2.7733935</td>
<td align="right">3.5680159</td>
<td align="right">7</td>
<td align="right">107</td>
<td align="right">0.0048843</td>
<td align="right">0.5605776</td>
</tr>
<tr class="even">
<td align="right">1.6120128</td>
<td align="right">2.3200362</td>
<td align="right">8</td>
<td align="right">94</td>
<td align="right">0.4933103</td>
<td align="right">-0.2789972</td>
</tr>
<tr class="odd">
<td align="right">3.5397356</td>
<td align="right">2.8607765</td>
<td align="right">7</td>
<td align="right">108</td>
<td align="right">0.0048843</td>
<td align="right">0.6251603</td>
</tr>
<tr class="even">
<td align="right">3.5275687</td>
<td align="right">2.8646434</td>
<td align="right">10</td>
<td align="right">109</td>
<td align="right">1.4701623</td>
<td align="right">0.6897430</td>
</tr>
</tbody>
</table></div>
</div>
<p>Now let's re-fit the model using the centered and scaled predictors.</p>
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">my_model_scaled</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">grade</span> <span class="op">~</span> <span class="va">lecture_c</span> <span class="op">+</span> <span class="va">nclicks_c</span>, <span class="va">grades2</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">my_model_scaled</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = grade ~ lecture_c + nclicks_c, data = grades2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.21653 -0.40603  0.02267  0.60720  1.38558 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.59839    0.08692  29.895   &lt;2e-16 ***
## lecture_c    0.18734    0.09370   1.999   0.0484 *  
## nclicks_c    0.07823    0.09370   0.835   0.4058    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.8692 on 97 degrees of freedom
## Multiple R-squared:  0.06543,    Adjusted R-squared:  0.04616 
## F-statistic: 3.395 on 2 and 97 DF,  p-value: 0.03756</code></pre>
<p>This tells us that lecture_c has a relatively larger influence; for each standard deviation increase in this variable, <code>grade</code> increases by about 0.19.</p>
</div>
<div id="model-comparison" class="section level3">
<h3>
<span class="header-section-number">3.1.6</span> Model comparison<a class="anchor" aria-label="anchor" href="#model-comparison"><i class="fas fa-link"></i></a>
</h3>
<p>Another common kind of question multiple regression is also used to address is of the form: Does some predictor or set of predictors of interest significantly impact my response variable <strong>over and above the effects of some control variables</strong>?</p>
<p>For example, we saw above that the model including <code>lecture</code> and <code>nclicks</code> was statistically significant,
<span class="math inline">\(F(2, 97) = 3.395\)</span>,
<span class="math inline">\(p = 0.038\)</span>.</p>
<p>The null hypothesis for a regression model with <span class="math inline">\(m\)</span> predictors is</p>
<p><span class="math display">\[H_0: \beta_1 = \beta_2 = \ldots = \beta_m = 0;\]</span></p>
<p>in other words, that all of the coefficients (except the intercept) are zero. If the null hypothesis is true, then the null model</p>
<p><span class="math display">\[Y_i = \beta_0\]</span></p>
<p>gives just as good of a prediction as the model including all of the predictors and their coefficients. In other words, your best prediction for <span class="math inline">\(Y\)</span> is just its mean (<span class="math inline">\(\mu_y\)</span>); the <span class="math inline">\(X\)</span> variables are irrelevant. We rejected this null hypothesis, which implies that we can do better by including our two predictors, <code>lecture</code> and <code>nclicks</code>.</p>
<p>But you might ask: maybe its the case that better students get better grades, and the relationship between <code>lecture</code>, <code>nclicks</code>, and <code>grade</code> is just mediated by student quality. After all, better students are more likely to go to lecture and download the materials. So we can ask, are attendance and downloads associated with better grades <strong>above and beyond</strong> student ability, as measured by GPA?</p>
<p>The way we can test this hypothesis is by using <strong>model comparison</strong>. The logic is as follows. First, estimate a model containing any control predictors but excluding the focal predictors of interest. Second, estimate a model containing the control predictors as well as the focal predictors. Finally, compare the two models, to see if there is any statistically significant gain by including the predictors.</p>
<p>Here is how you do this:</p>
<div class="sourceCode" id="cb54"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">m1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">grade</span> <span class="op">~</span> <span class="va">GPA</span>, <span class="va">grades</span><span class="op">)</span> <span class="co"># control model</span>
<span class="va">m2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">grade</span> <span class="op">~</span> <span class="va">GPA</span> <span class="op">+</span> <span class="va">lecture</span> <span class="op">+</span> <span class="va">nclicks</span>, <span class="va">grades</span><span class="op">)</span> <span class="co"># bigger model</span>

<span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">m1</span>, <span class="va">m2</span><span class="op">)</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="right">Res.Df</th>
<th align="right">RSS</th>
<th align="right">Df</th>
<th align="right">Sum of Sq</th>
<th align="right">F</th>
<th align="right">Pr(&gt;F)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">98</td>
<td align="right">73.52823</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="right">96</td>
<td align="right">71.57829</td>
<td align="right">2</td>
<td align="right">1.949939</td>
<td align="right">1.307618</td>
<td align="right">0.2752366</td>
</tr>
</tbody>
</table></div>
</div>
<p>The null hypothesis is that we are just as good predicting <code>grade</code> from <code>GPA</code> as we are predicting it from <code>GPA</code> plus <code>lecture</code> and <code>nclicks</code>. We will reject the null if adding these two variables leads to a substantial enough reduction in the <strong>residual sums of squares</strong> (RSS); i.e., if they explain away enough residual variance.</p>
<p>We see that this is not the case:
<span class="math inline">\(F(2, 96 ) = 1.308\)</span>,
<span class="math inline">\(p = 0.275\)</span>. So we don't have evidence that lecture attendance and downloading the online materials is associated with better grades above and beyond student ability, as measured by GPA.</p>
</div>
</div>
<div id="dealing-with-categorical-predictors" class="section level2">
<h2>
<span class="header-section-number">3.2</span> Dealing with categorical predictors<a class="anchor" aria-label="anchor" href="#dealing-with-categorical-predictors"><i class="fas fa-link"></i></a>
</h2>
<p>You can include categorical predictors in a regression model, but first you have to code them as numerical variables. There are a couple of important considerations here.</p>
<div type="danger">
<p>A <strong>nominal</strong> variable is a categorical variable for which there is no inherent ordering among the levels of the variable. Pet ownership (cat, dog, ferret) is a nominal variable; cat is not greater than dog and dog is not greater than ferret.</p>
<p>It is common to code nominal variables using numbers. However, you have to be <strong>very careful</strong> about using numerically-coded nominal variables in your models. If you have a number that is really just a nominal variable, make sure you define it as type <code><a href="https://rdrr.io/r/base/factor.html">factor()</a></code> before entering it into the model. Otherwise, it will try to treat it as an actual number, and the results of your modeling will be garbage!</p>
<p>It is far too easy to make this mistake, and difficult to catch if authors do not share their data and code. In 2016, <a href="https://www.sciencedirect.com/science/article/pii/S0960982216306704">a paper on religious affiliation and altruism in children that was published in Current Biology had to be retracted for just this kind of mistake</a>.</p>
</div>
<div id="dummy-coding" class="section level3">
<h3>
<span class="header-section-number">3.2.1</span> Dummy coding<a class="anchor" aria-label="anchor" href="#dummy-coding"><i class="fas fa-link"></i></a>
</h3>
<p>For a factor with two levels, choose one level as zero and the other as one. The choice is arbitrary, and will affect the sign of the coefficient, but not its standard error or p-value. Here is some code that will do this. Note that if you have a predictor of type character or factor, R will automatically do that for you. We don't want R to do this for reasons that will become apparent in the next lecture, so let's learn how to make our own numeric predictor.</p>
<p>First, we gin up some fake data to use in our analysis.</p>
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fake_data</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>Y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">10</span><span class="op">)</span>,
                    group <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"A"</span>, <span class="st">"B"</span><span class="op">)</span>, each <span class="op">=</span> <span class="fl">5</span><span class="op">)</span><span class="op">)</span>

<span class="va">fake_data</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="right">Y</th>
<th align="left">group</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">0.4827963</td>
<td align="left">A</td>
</tr>
<tr class="even">
<td align="right">-0.5740740</td>
<td align="left">A</td>
</tr>
<tr class="odd">
<td align="right">0.5878810</td>
<td align="left">A</td>
</tr>
<tr class="even">
<td align="right">-0.7380709</td>
<td align="left">A</td>
</tr>
<tr class="odd">
<td align="right">-0.3078509</td>
<td align="left">A</td>
</tr>
<tr class="even">
<td align="right">-0.0508260</td>
<td align="left">B</td>
</tr>
<tr class="odd">
<td align="right">-0.8307008</td>
<td align="left">B</td>
</tr>
<tr class="even">
<td align="right">-1.6521542</td>
<td align="left">B</td>
</tr>
<tr class="odd">
<td align="right">-0.3067577</td>
<td align="left">B</td>
</tr>
<tr class="even">
<td align="right">1.0981488</td>
<td align="left">B</td>
</tr>
</tbody>
</table></div>
</div>
<p>Now let's add a new variable, <code>group_d</code>, which is the dummy coded group variable. We will use the <code><a href="https://dplyr.tidyverse.org/reference/if_else.html">dplyr::if_else()</a></code> function to define the new column.</p>
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fake_data2</span> <span class="op">&lt;-</span> <span class="va">fake_data</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>group_d <span class="op">=</span> <span class="fu">if_else</span><span class="op">(</span><span class="va">group</span> <span class="op">==</span> <span class="st">"B"</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span><span class="op">)</span>

<span class="va">fake_data2</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="right">Y</th>
<th align="left">group</th>
<th align="right">group_d</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">0.4827963</td>
<td align="left">A</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">-0.5740740</td>
<td align="left">A</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">0.5878810</td>
<td align="left">A</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">-0.7380709</td>
<td align="left">A</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">-0.3078509</td>
<td align="left">A</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">-0.0508260</td>
<td align="left">B</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="right">-0.8307008</td>
<td align="left">B</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">-1.6521542</td>
<td align="left">B</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="right">-0.3067577</td>
<td align="left">B</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">1.0981488</td>
<td align="left">B</td>
<td align="right">1</td>
</tr>
</tbody>
</table></div>
</div>
<p>Now we just run it as a regular regression model.</p>
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">group_d</span>, <span class="va">fake_data2</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y ~ group_d, data = fake_data2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.30370 -0.47773 -0.07814  0.51890  1.44661 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  -0.1099     0.3743  -0.294    0.777
## group_d      -0.2386     0.5293  -0.451    0.664
## 
## Residual standard error: 0.8369 on 8 degrees of freedom
## Multiple R-squared:  0.02477,    Adjusted R-squared:  -0.09713 
## F-statistic: 0.2032 on 1 and 8 DF,  p-value: 0.6641</code></pre>
<p>Note that if we reverse the coding we get the same result, just the sign is different.</p>
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fake_data3</span> <span class="op">&lt;-</span> <span class="va">fake_data</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>group_d <span class="op">=</span> <span class="fu">if_else</span><span class="op">(</span><span class="va">group</span> <span class="op">==</span> <span class="st">"A"</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">group_d</span>, <span class="va">fake_data3</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y ~ group_d, data = fake_data3)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.30370 -0.47773 -0.07814  0.51890  1.44661 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  -0.3485     0.3743  -0.931    0.379
## group_d       0.2386     0.5293   0.451    0.664
## 
## Residual standard error: 0.8369 on 8 degrees of freedom
## Multiple R-squared:  0.02477,    Adjusted R-squared:  -0.09713 
## F-statistic: 0.2032 on 1 and 8 DF,  p-value: 0.6641</code></pre>
<p>The interpretation of the intercept is the estimated mean for the group coded as zero. You can see by plugging in zero for X in the prediction formula below. Thus, <span class="math inline">\(\beta_1\)</span> can be interpreted as the difference between the mean for the baseline group and the group coded as 1.</p>
<p><span class="math display">\[\hat{Y_i} = \hat{\beta}_0 + \hat{\beta}_1 X_i \]</span></p>
<!--
<div type="info">

Why not just use **factors** as your predictors?

</div>
-->
</div>
<div id="dummy-coding-when-k-2" class="section level3">
<h3>
<span class="header-section-number">3.2.2</span> Dummy coding when <span class="math inline">\(k &gt; 2\)</span><a class="anchor" aria-label="anchor" href="#dummy-coding-when-k-2"><i class="fas fa-link"></i></a>
</h3>
<p>When the predictor variable is a factor with <span class="math inline">\(k\)</span> levels where <span class="math inline">\(k&gt;2\)</span>, we need <span class="math inline">\(k-1\)</span> predictors to code that variable. So if the factor has 4 levels, we'll need to define three predictors. Here is code to do that. Try it out and see if you can figure out how it works.</p>
<div class="sourceCode" id="cb61"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mydata</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>season <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"winter"</span>, <span class="st">"spring"</span>, <span class="st">"summer"</span>, <span class="st">"fall"</span><span class="op">)</span>, each <span class="op">=</span> <span class="fl">5</span><span class="op">)</span>,
                 bodyweight_kg <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">105</span>, <span class="fl">3</span><span class="op">)</span>,
                                   <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">103</span>, <span class="fl">3</span><span class="op">)</span>,
                                   <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">101</span>, <span class="fl">3</span><span class="op">)</span>,
                                   <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">102.5</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>

<span class="va">mydata</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">season</th>
<th align="right">bodyweight_kg</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">winter</td>
<td align="right">104.06775</td>
</tr>
<tr class="even">
<td align="left">winter</td>
<td align="right">106.02152</td>
</tr>
<tr class="odd">
<td align="left">winter</td>
<td align="right">102.34202</td>
</tr>
<tr class="even">
<td align="left">winter</td>
<td align="right">102.12390</td>
</tr>
<tr class="odd">
<td align="left">winter</td>
<td align="right">102.84049</td>
</tr>
<tr class="even">
<td align="left">spring</td>
<td align="right">99.26328</td>
</tr>
<tr class="odd">
<td align="left">spring</td>
<td align="right">100.93551</td>
</tr>
<tr class="even">
<td align="left">spring</td>
<td align="right">99.64912</td>
</tr>
<tr class="odd">
<td align="left">spring</td>
<td align="right">103.64669</td>
</tr>
<tr class="even">
<td align="left">spring</td>
<td align="right">107.41195</td>
</tr>
<tr class="odd">
<td align="left">summer</td>
<td align="right">102.73417</td>
</tr>
<tr class="even">
<td align="left">summer</td>
<td align="right">105.78966</td>
</tr>
<tr class="odd">
<td align="left">summer</td>
<td align="right">98.66112</td>
</tr>
<tr class="even">
<td align="left">summer</td>
<td align="right">103.88219</td>
</tr>
<tr class="odd">
<td align="left">summer</td>
<td align="right">101.56537</td>
</tr>
<tr class="even">
<td align="left">fall</td>
<td align="right">101.13225</td>
</tr>
<tr class="odd">
<td align="left">fall</td>
<td align="right">105.23585</td>
</tr>
<tr class="even">
<td align="left">fall</td>
<td align="right">103.14270</td>
</tr>
<tr class="odd">
<td align="left">fall</td>
<td align="right">104.94464</td>
</tr>
<tr class="even">
<td align="left">fall</td>
<td align="right">101.34257</td>
</tr>
</tbody>
</table></div>
</div>
<p>Now let's add three predictors to code the variable <code>season</code>.</p>
<div class="sourceCode" id="cb62"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## baseline value is 'winter'</span>
<span class="va">mydata2</span> <span class="op">&lt;-</span> <span class="va">mydata</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>V1 <span class="op">=</span> <span class="fu">if_else</span><span class="op">(</span><span class="va">season</span> <span class="op">==</span> <span class="st">"spring"</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span>,
         V2 <span class="op">=</span> <span class="fu">if_else</span><span class="op">(</span><span class="va">season</span> <span class="op">==</span> <span class="st">"summer"</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span>,
         V3 <span class="op">=</span> <span class="fu">if_else</span><span class="op">(</span><span class="va">season</span> <span class="op">==</span> <span class="st">"fall"</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span><span class="op">)</span>

<span class="va">mydata2</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">season</th>
<th align="right">bodyweight_kg</th>
<th align="right">V1</th>
<th align="right">V2</th>
<th align="right">V3</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">winter</td>
<td align="right">104.06775</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">winter</td>
<td align="right">106.02152</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">winter</td>
<td align="right">102.34202</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">winter</td>
<td align="right">102.12390</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">winter</td>
<td align="right">102.84049</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">spring</td>
<td align="right">99.26328</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">spring</td>
<td align="right">100.93551</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">spring</td>
<td align="right">99.64912</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">spring</td>
<td align="right">103.64669</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">spring</td>
<td align="right">107.41195</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">summer</td>
<td align="right">102.73417</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">summer</td>
<td align="right">105.78966</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">summer</td>
<td align="right">98.66112</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">summer</td>
<td align="right">103.88219</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">summer</td>
<td align="right">101.56537</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">fall</td>
<td align="right">101.13225</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">fall</td>
<td align="right">105.23585</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">fall</td>
<td align="right">103.14270</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">fall</td>
<td align="right">104.94464</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">fall</td>
<td align="right">101.34257</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
</tr>
</tbody>
</table></div>
</div>
</div>
</div>
<div id="equivalence-between-multiple-regression-and-one-way-anova" class="section level2">
<h2>
<span class="header-section-number">3.3</span> Equivalence between multiple regression and one-way ANOVA<a class="anchor" aria-label="anchor" href="#equivalence-between-multiple-regression-and-one-way-anova"><i class="fas fa-link"></i></a>
</h2>
<p>If we wanted to see whether our bodyweight varies over season, we could do a one way ANOVA on <code>mydata2</code> like so.</p>
<div class="sourceCode" id="cb63"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## make season into a factor with baseline level 'winter'</span>
<span class="va">mydata3</span> <span class="op">&lt;-</span> <span class="va">mydata2</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>season <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">season</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"winter"</span>, <span class="st">"spring"</span>, <span class="st">"summer"</span>, <span class="st">"fall"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>

<span class="va">my_anova</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">bodyweight_kg</span> <span class="op">~</span> <span class="va">season</span>, <span class="va">mydata3</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">my_anova</span><span class="op">)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## season       3   5.21   1.738   0.279   0.84
## Residuals   16  99.64   6.227</code></pre>
<p>OK, now can we replicate that result using the regression model below?</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1 X_{1i} + \beta_2 X_{2i} + \beta_3 X_{3i} + e_i\]</span></p>
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">bodyweight_kg</span> <span class="op">~</span> <span class="va">V1</span> <span class="op">+</span> <span class="va">V2</span> <span class="op">+</span> <span class="va">V3</span>, <span class="va">mydata3</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = bodyweight_kg ~ V1 + V2 + V3, data = mydata3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.8654 -1.4707 -0.3278  1.5453  5.2306 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 103.4791     1.1160  92.723   &lt;2e-16 ***
## V1           -1.2978     1.5783  -0.822    0.423    
## V2           -0.9526     1.5783  -0.604    0.555    
## V3           -0.3195     1.5783  -0.202    0.842    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.495 on 16 degrees of freedom
## Multiple R-squared:  0.04973,    Adjusted R-squared:  -0.1285 
## F-statistic: 0.2791 on 3 and 16 DF,  p-value: 0.8397</code></pre>
<p>Note that the <span class="math inline">\(F\)</span> values and <span class="math inline">\(p\)</span> values are identical for the two methods!</p>
</div>
<div id="solution-to-partial-effect-plot" class="section level2">
<h2>
<span class="header-section-number">3.4</span> Solution to partial effect plot<a class="anchor" aria-label="anchor" href="#solution-to-partial-effect-plot"><i class="fas fa-link"></i></a>
</h2>
<p>First create a tibble with new predictors. We might also want to know the range of values that <code>nclicks</code> varies over.</p>
<div class="sourceCode" id="cb67"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lecture_mean</span> <span class="op">&lt;-</span> <span class="va">grades</span> <span class="op">%&gt;%</span> <span class="fu">pull</span><span class="op">(</span><span class="va">lecture</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="op">)</span>
<span class="va">min_nclicks</span> <span class="op">&lt;-</span> <span class="va">grades</span> <span class="op">%&gt;%</span> <span class="fu">pull</span><span class="op">(</span><span class="va">nclicks</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="op">)</span>
<span class="va">max_nclicks</span> <span class="op">&lt;-</span> <span class="va">grades</span> <span class="op">%&gt;%</span> <span class="fu">pull</span><span class="op">(</span><span class="va">nclicks</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="op">)</span>

<span class="co">## new data for prediction</span>
<span class="va">new_nclicks</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>lecture <span class="op">=</span> <span class="va">lecture_mean</span>,
                      nclicks <span class="op">=</span> <span class="va">min_nclicks</span><span class="op">:</span><span class="va">max_nclicks</span><span class="op">)</span>

<span class="co">## add the predicted value to new_lecture</span>
<span class="va">new_nclicks2</span> <span class="op">&lt;-</span> <span class="va">new_nclicks</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>grade <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">my_model</span>, <span class="va">new_nclicks</span><span class="op">)</span><span class="op">)</span>

<span class="va">new_nclicks2</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="right">lecture</th>
<th align="right">nclicks</th>
<th align="right">grade</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">54</td>
<td align="right">2.374462</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">55</td>
<td align="right">2.379514</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">56</td>
<td align="right">2.384567</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">57</td>
<td align="right">2.389619</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">58</td>
<td align="right">2.394672</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">59</td>
<td align="right">2.399724</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">60</td>
<td align="right">2.404777</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">61</td>
<td align="right">2.409829</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">62</td>
<td align="right">2.414882</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">63</td>
<td align="right">2.419934</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">64</td>
<td align="right">2.424987</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">65</td>
<td align="right">2.430039</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">66</td>
<td align="right">2.435092</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">67</td>
<td align="right">2.440144</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">68</td>
<td align="right">2.445197</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">69</td>
<td align="right">2.450249</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">70</td>
<td align="right">2.455302</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">71</td>
<td align="right">2.460354</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">72</td>
<td align="right">2.465407</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">73</td>
<td align="right">2.470459</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">74</td>
<td align="right">2.475512</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">75</td>
<td align="right">2.480564</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">76</td>
<td align="right">2.485617</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">77</td>
<td align="right">2.490669</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">78</td>
<td align="right">2.495722</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">79</td>
<td align="right">2.500774</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">80</td>
<td align="right">2.505827</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">81</td>
<td align="right">2.510879</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">82</td>
<td align="right">2.515932</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">83</td>
<td align="right">2.520984</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">84</td>
<td align="right">2.526037</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">85</td>
<td align="right">2.531089</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">86</td>
<td align="right">2.536142</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">87</td>
<td align="right">2.541194</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">88</td>
<td align="right">2.546247</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">89</td>
<td align="right">2.551299</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">90</td>
<td align="right">2.556352</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">91</td>
<td align="right">2.561404</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">92</td>
<td align="right">2.566457</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">93</td>
<td align="right">2.571509</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">94</td>
<td align="right">2.576562</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">95</td>
<td align="right">2.581614</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">96</td>
<td align="right">2.586667</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">97</td>
<td align="right">2.591719</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">98</td>
<td align="right">2.596772</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">99</td>
<td align="right">2.601824</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">100</td>
<td align="right">2.606876</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">101</td>
<td align="right">2.611929</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">102</td>
<td align="right">2.616982</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">103</td>
<td align="right">2.622034</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">104</td>
<td align="right">2.627086</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">105</td>
<td align="right">2.632139</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">106</td>
<td align="right">2.637192</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">107</td>
<td align="right">2.642244</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">108</td>
<td align="right">2.647296</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">109</td>
<td align="right">2.652349</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">110</td>
<td align="right">2.657402</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">111</td>
<td align="right">2.662454</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">112</td>
<td align="right">2.667506</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">113</td>
<td align="right">2.672559</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">114</td>
<td align="right">2.677611</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">115</td>
<td align="right">2.682664</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">116</td>
<td align="right">2.687716</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">117</td>
<td align="right">2.692769</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">118</td>
<td align="right">2.697821</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">119</td>
<td align="right">2.702874</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">120</td>
<td align="right">2.707926</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">121</td>
<td align="right">2.712979</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">122</td>
<td align="right">2.718031</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">123</td>
<td align="right">2.723084</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">124</td>
<td align="right">2.728136</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">125</td>
<td align="right">2.733189</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">126</td>
<td align="right">2.738241</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">127</td>
<td align="right">2.743294</td>
</tr>
<tr class="odd">
<td align="right">6.99</td>
<td align="right">128</td>
<td align="right">2.748346</td>
</tr>
<tr class="even">
<td align="right">6.99</td>
<td align="right">129</td>
<td align="right">2.753399</td>
</tr>
</tbody>
</table></div>
</div>
<p>Now plot.</p>
<div class="sourceCode" id="cb68"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="va">grades</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">nclicks</span>, <span class="va">grade</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_line</span><span class="op">(</span>data <span class="op">=</span> <span class="va">new_nclicks2</span><span class="op">)</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:partial-nclicks"></span>
<img src="03-multiple-regression_files/figure-html/partial-nclicks-1.png" alt="Partial effect plot of nclicks on grade." width="100%"><p class="caption">
Figure 3.2: Partial effect plot of nclicks on grade.
</p>
</div>

</div>
</div>
<div class="psyteachr_footer">
  
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  if (t = document.getElementById("webex-total_correct")) {
    t.innerHTML =
      document.getElementsByClassName("webex-correct").length + " of " +
      document.getElementsByClassName("webex-solveme").length + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }
  
  if (my_answer !== "" & real_answers.includes(my_answer)) {
    cl.add("webex-correct");
  } else {
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);  
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }  
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }  
  }
  
  update_total_correct();
}

window.onload = function() {
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }
  
  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off"); 
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";
    
    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;
    
    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  update_total_correct();
}

</script><div class="chapter-nav">
<div class="prev"><a href="understanding-correlation-and-regression-through-bivariate-simulation.html"><span class="header-section-number">2</span> Understanding correlation and regression through bivariate simulation</a></div>
<div class="next"><a href="interactions.html"><span class="header-section-number">4</span> Interactions</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#multiple-regression"><span class="header-section-number">3</span> Multiple regression</a></li>
<li>
<a class="nav-link" href="#an-example-how-to-get-a-good-grade-in-statistics"><span class="header-section-number">3.1</span> An example: How to get a good grade in statistics</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#data-import-and-visualization"><span class="header-section-number">3.1.1</span> Data import and visualization</a></li>
<li><a class="nav-link" href="#estimation-and-interpretation"><span class="header-section-number">3.1.2</span> Estimation and interpretation</a></li>
<li><a class="nav-link" href="#predictions-from-the-linear-model-using-predict"><span class="header-section-number">3.1.3</span> Predictions from the linear model using predict()</a></li>
<li><a class="nav-link" href="#visualizing-partial-effects"><span class="header-section-number">3.1.4</span> Visualizing partial effects</a></li>
<li><a class="nav-link" href="#standardizing-coefficients"><span class="header-section-number">3.1.5</span> Standardizing coefficients</a></li>
<li><a class="nav-link" href="#model-comparison"><span class="header-section-number">3.1.6</span> Model comparison</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#dealing-with-categorical-predictors"><span class="header-section-number">3.2</span> Dealing with categorical predictors</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#dummy-coding"><span class="header-section-number">3.2.1</span> Dummy coding</a></li>
<li><a class="nav-link" href="#dummy-coding-when-k-2"><span class="header-section-number">3.2.2</span> Dummy coding when \(k &gt; 2\)</a></li>
</ul>
</li>
<li><a class="nav-link" href="#equivalence-between-multiple-regression-and-one-way-anova"><span class="header-section-number">3.3</span> Equivalence between multiple regression and one-way ANOVA</a></li>
<li><a class="nav-link" href="#solution-to-partial-effect-plot"><span class="header-section-number">3.4</span> Solution to partial effect plot</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Learning Statistical Models Through Simulation in R</strong>" was written by Dale J. Barr. It was last built on 2021-08-25.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
