<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 2 Understanding correlation and regression through bivariate simulation | Learning Statistical Models Through Simulation in R</title>
<meta name="author" content="Dale J. Barr">
<meta name="description" content="2.1 Correlation matrices You may be familiar with the concept of a correlation matrix from reading papers in psychology. Correlation matrices are a common way of summarizing relationships between...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Chapter 2 Understanding correlation and regression through bivariate simulation | Learning Statistical Models Through Simulation in R">
<meta property="og:type" content="book">
<meta property="og:url" content="https://psyteachr.github.io/stat-models-v1/understanding-correlation-and-regression-through-bivariate-simulation.html">
<meta property="og:image" content="https://psyteachr.github.io/stat-models-v1/images/logos/logo.png">
<meta property="og:description" content="2.1 Correlation matrices You may be familiar with the concept of a correlation matrix from reading papers in psychology. Correlation matrices are a common way of summarizing relationships between...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 2 Understanding correlation and regression through bivariate simulation | Learning Statistical Models Through Simulation in R">
<meta name="twitter:description" content="2.1 Correlation matrices You may be familiar with the concept of a correlation matrix from reading papers in psychology. Correlation matrices are a common way of summarizing relationships between...">
<meta name="twitter:image" content="https://psyteachr.github.io/stat-models-v1/images/logos/logo.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.0/transition.js"></script><script src="libs/bs3compat-0.3.0/tabs.js"></script><script src="libs/bs3compat-0.3.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script><script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'G-6NP3MF25W3');
  </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="include/psyteachr.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Learning Statistical Models Through Simulation in R</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Overview</a></li>
<li><a class="" href="introduction.html"><span class="header-section-number">1</span> Introduction</a></li>
<li><a class="active" href="understanding-correlation-and-regression-through-bivariate-simulation.html"><span class="header-section-number">2</span> Understanding correlation and regression through bivariate simulation</a></li>
<li><a class="" href="multiple-regression.html"><span class="header-section-number">3</span> Multiple regression</a></li>
<li><a class="" href="interactions.html"><span class="header-section-number">4</span> Interactions</a></li>
<li><a class="" href="introducing-linear-mixed-effects-models.html"><span class="header-section-number">5</span> Introducing Linear Mixed-Effects Models</a></li>
<li><a class="" href="linear-mixed-effects-models-with-one-random-factor.html"><span class="header-section-number">6</span> Linear mixed-effects models with one random factor</a></li>
<li><a class="" href="linear-mixed-effects-models-with-crossed-random-factors.html"><span class="header-section-number">7</span> Linear mixed-effects models with crossed random factors</a></li>
<li><a class="" href="generalized-linear-mixed-effects-models.html"><span class="header-section-number">8</span> Generalized linear mixed-effects models</a></li>
<li><a class="" href="modeling-ordinal-data.html"><span class="header-section-number">9</span> Modeling Ordinal Data</a></li>
<li class="book-part">Appendix</li>
<li><a class="" href="symbols.html"><span class="header-section-number">A</span> Symbols</a></li>
<li><a class="" href="bibliography.html"><span class="header-section-number">B</span> Bibliography</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/psyteachr/stat-models-v1">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="understanding-correlation-and-regression-through-bivariate-simulation" class="section level1">
<h1>
<span class="header-section-number">2</span> Understanding correlation and regression through bivariate simulation<a class="anchor" aria-label="anchor" href="#understanding-correlation-and-regression-through-bivariate-simulation"><i class="fas fa-link"></i></a>
</h1>
<div id="correlation-matrices" class="section level2">
<h2>
<span class="header-section-number">2.1</span> Correlation matrices<a class="anchor" aria-label="anchor" href="#correlation-matrices"><i class="fas fa-link"></i></a>
</h2>
<p>You may be familiar with the concept of a <strong>correlation matrix</strong> from reading papers in psychology. Correlation matrices are a common way of summarizing relationships between multiple measurements taken from the same individual.</p>
<p>Let's say you've measured psychological well-being using multiple scales. One question is the extent to which these scales are measuring the same thing. Often you will look at a correlation matrix to explore all the pairwise relationships between measures.</p>
<p>Recall that a correlation coefficient quantifies the <strong>strength</strong> and <strong>direction</strong> of a relationship between two variables. It is usually represented by the symbol <span class="math inline">\(r\)</span> or <span class="math inline">\(\rho\)</span> (Greek letter "rho"). The correlation coefficient ranges between -1 and 1, with 0 corresponding to no relationship, positive values reflecting a positive relationship (as one variable increases, so does the other), and negative values reflecting a negative relationship (as one variable increases, the other decreases).</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:correlation-relationships"></span>
<img src="02-bivariate-simulation_files/figure-html/correlation-relationships-1.png" alt="Different types of bivariate relationships." width="100%"><p class="caption">
Figure 2.1: Different types of bivariate relationships.
</p>
</div>
<p>If you have <span class="math inline">\(n\)</span> measures, how many pairwise correlations can you compute? You can figure this out either by the formula in the info box below, or more easily you can computed it directly through the <code><a href="https://rdrr.io/r/base/Special.html">choose(n, 2)</a></code> function in R. For instance, to get the number of possible pairwise correlations between 6 measures, you'd type <code><a href="https://rdrr.io/r/base/Special.html">choose(6, 2)</a></code>, which tells you that you have 15 combinations.</p>
<div class="info">
<p>
For any <span class="math inline"><span class="math inline">\(n\)</span></span> measures, you can calculate <span class="math inline"><span class="math inline">\(\frac{n!}{2(n - 2)!}\)</span></span> pairwise correlations between measures. The <span class="math inline"><span class="math inline">\(!\)</span></span> symbol is called the <strong>factorial</strong> operator, defined as the product of all numbers from 1 to <span class="math inline"><span class="math inline">\(n\)</span></span>. So, if you have six measurements, you have
</p>
<p>
<span class="math display"><span class="math display">\[
\frac{6!}{2(6-2)!} = \frac{1 \times 2 \times 3 \times 4 \times 5 \times 6}{2\left(1 \times 2 \times 3 \times 4\right)} = \frac{720}{2(24)} = 15
\]</span></span>
</p>
</div>
<p>You can create a correlation matrix in R using <code>base::cor()</code> or <code><a href="https://corrr.tidymodels.org/reference/correlate.html">corrr::correlate()</a></code>. We prefer the latter function because <code><a href="https://rdrr.io/r/stats/cor.html">cor()</a></code> requires that your data is stored in a matrix, whereas most of the data we will be working with is tabular data stored in a data frame. The <code><a href="https://corrr.tidymodels.org/reference/correlate.html">corrr::correlate()</a></code> function takes a data frame as the first argument, and provides "tidy" output, so it integrates better with tidyverse functions and pipes (<code>%&gt;%</code>).</p>
<p>Let's create a correlation matrix to see how it works. Start by loading in the packages we will need.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://tidyverse.tidyverse.org">"tidyverse"</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/tidymodels/corrr">"corrr"</a></span><span class="op">)</span>  <span class="co"># install.packages("corrr") in console if missing</span></code></pre></div>
<p>We will use the <code>starwars</code> dataset, which is a built-in dataset that becomes available after you load the tidyverse package. This dataset has information about various characters that have appeared in the Star Wars film series. Let's look at the correlation between</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu">select</span><span class="op">(</span><span class="va">height</span>, <span class="va">mass</span>, <span class="va">birth_year</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/correlate.html">correlate</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Correlation method: 'pearson'
## Missing treated using: 'pairwise.complete.obs'</code></pre>
<pre><code>## # A tibble: 3 × 4
##   term       height   mass birth_year
##   &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;
## 1 height     NA      0.134     -0.400
## 2 mass        0.134 NA          0.478
## 3 birth_year -0.400  0.478     NA</code></pre>
<p>You can look up any bivariate correlation at the intersection of any given row or column. So the correlation between <code>height</code> and <code>mass</code> is .134, which you can find in row 1, column 2 or row 2, column 1; the values are the same. Note that there are only <code><a href="https://rdrr.io/r/base/Special.html">choose(3, 2)</a></code> = 3 unique bivariate relationships, but each appears twice in the table. We might want to show only the unique pairs. We can do this by appending <code><a href="https://corrr.tidymodels.org/reference/shave.html">corrr::shave()</a></code> to our pipeline.</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu">select</span><span class="op">(</span><span class="va">height</span>, <span class="va">mass</span>, <span class="va">birth_year</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/correlate.html">correlate</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/shave.html">shave</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Correlation method: 'pearson'
## Missing treated using: 'pairwise.complete.obs'</code></pre>
<pre><code>## # A tibble: 3 × 4
##   term       height   mass birth_year
##   &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;
## 1 height     NA     NA             NA
## 2 mass        0.134 NA             NA
## 3 birth_year -0.400  0.478         NA</code></pre>
<p>Now we've only got the lower triangle of the correlation matrix, but the <code>NA</code> values are ugly and so are the leading zeroes. The <strong><code>corrr</code></strong> package also provides the <code><a href="https://corrr.tidymodels.org/reference/fashion.html">fashion()</a></code> function that cleans things up (see <code><a href="https://corrr.tidymodels.org/reference/fashion.html">?corrr::fashion</a></code> for more options).</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu">select</span><span class="op">(</span><span class="va">height</span>, <span class="va">mass</span>, <span class="va">birth_year</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/correlate.html">correlate</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/shave.html">shave</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/fashion.html">fashion</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Correlation method: 'pearson'
## Missing treated using: 'pairwise.complete.obs'</code></pre>
<pre><code>##         term height mass birth_year
## 1     height                       
## 2       mass    .13                
## 3 birth_year   -.40  .48</code></pre>
<p>Correlations only provide a good description of the relationship if the relationship is (roughly) linear and there aren't severe outliers that are wielding too strong of an influence on the results. So it is always a good idea to visualize the correlations as well as to quantify them. The <code>base::pairs()</code> function does this. The first argument to <code><a href="https://rdrr.io/r/graphics/pairs.html">pairs()</a></code> is simply of the form <code>~ v1 + v2 + v3 + ... + vn</code> where <code>v1</code>, <code>v2</code>, etc. are the names of the variables you want to correlate.</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/pairs.html">pairs</a></span><span class="op">(</span><span class="op">~</span> <span class="va">height</span> <span class="op">+</span> <span class="va">mass</span> <span class="op">+</span> <span class="va">birth_year</span>, <span class="va">starwars</span><span class="op">)</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:pairs"></span>
<img src="02-bivariate-simulation_files/figure-html/pairs-1.png" alt="Pairwise correlations for the starwars dataset" width="100%"><p class="caption">
Figure 2.2: Pairwise correlations for the starwars dataset
</p>
</div>
<p>We can see that there is a big outlier influencing our data; in particular, there is a creature with a mass greater than 1200kg! Let's find out who this is and eliminate them from the dataset.</p>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">mass</span> <span class="op">&gt;</span> <span class="fl">1200</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">select</span><span class="op">(</span><span class="va">name</span>, <span class="va">mass</span>, <span class="va">height</span>, <span class="va">birth_year</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##   name                   mass height birth_year
##   &lt;chr&gt;                 &lt;dbl&gt;  &lt;int&gt;      &lt;dbl&gt;
## 1 Jabba Desilijic Tiure  1358    175        600</code></pre>
<p>OK, let's see how the data look without this massive creature.</p>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars2</span> <span class="op">&lt;-</span> <span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">name</span> <span class="op">!=</span> <span class="st">"Jabba Desilijic Tiure"</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/graphics/pairs.html">pairs</a></span><span class="op">(</span><span class="op">~</span><span class="va">height</span> <span class="op">+</span> <span class="va">mass</span> <span class="op">+</span> <span class="va">birth_year</span>, <span class="va">starwars2</span><span class="op">)</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:massive-creature"></span>
<img src="02-bivariate-simulation_files/figure-html/massive-creature-1.png" alt="Pairwise correlations for the starwars dataset after removing outlying mass value." width="100%"><p class="caption">
Figure 2.3: Pairwise correlations for the starwars dataset after removing outlying mass value.
</p>
</div>
<p>Better, but there's a creature with an outlying birth year that we might want to get rid of.</p>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars2</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">birth_year</span> <span class="op">&gt;</span> <span class="fl">800</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">select</span><span class="op">(</span><span class="va">name</span>, <span class="va">height</span>, <span class="va">mass</span>, <span class="va">birth_year</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##   name  height  mass birth_year
##   &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt;      &lt;dbl&gt;
## 1 Yoda      66    17        896</code></pre>
<p>It's Yoda. He's as old as the universe. Let's drop him and see how the plots look.</p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars3</span> <span class="op">&lt;-</span> <span class="va">starwars2</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">name</span> <span class="op">!=</span> <span class="st">"Yoda"</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/graphics/pairs.html">pairs</a></span><span class="op">(</span><span class="op">~</span><span class="va">height</span> <span class="op">+</span> <span class="va">mass</span> <span class="op">+</span> <span class="va">birth_year</span>, <span class="va">starwars3</span><span class="op">)</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:bye-yoda"></span>
<img src="02-bivariate-simulation_files/figure-html/bye-yoda-1.png" alt="Pairwise correlations for the starwars dataset after removing outlying mass and birth\_year values." width="100%"><p class="caption">
Figure 2.4: Pairwise correlations for the starwars dataset after removing outlying mass and birth_year values.
</p>
</div>
<p>That looks much better. Let's see how that changes our correlation matrix.</p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars3</span> <span class="op">%&gt;%</span>
  <span class="fu">select</span><span class="op">(</span><span class="va">height</span>, <span class="va">mass</span>, <span class="va">birth_year</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/correlate.html">correlate</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/shave.html">shave</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/fashion.html">fashion</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Correlation method: 'pearson'
## Missing treated using: 'pairwise.complete.obs'</code></pre>
<pre><code>##         term height mass birth_year
## 1     height                       
## 2       mass    .74                
## 3 birth_year    .45  .24</code></pre>
<p>Note that these values are quite different from the ones we started with.</p>
<p>Sometimes it's not a great idea to remove outliers. Another approach to dealing with outliers is to use a robust method. The default correlation coefficient that is computed by <code><a href="https://corrr.tidymodels.org/reference/correlate.html">corrr::correlate()</a></code> is the Pearson product-moment correlation coefficient. You can also compute the Spearman correlation coefficient by changing the <code>method()</code> argument to <code><a href="https://corrr.tidymodels.org/reference/correlate.html">correlate()</a></code>. This replaces the values with ranks before computing the correlation, so that outliers will still be included, but will have dramatically less influence.</p>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu">select</span><span class="op">(</span><span class="va">height</span>, <span class="va">mass</span>, <span class="va">birth_year</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/correlate.html">correlate</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"spearman"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/shave.html">shave</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/fashion.html">fashion</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Correlation method: 'spearman'
## Missing treated using: 'pairwise.complete.obs'</code></pre>
<pre><code>##         term height mass birth_year
## 1     height                       
## 2       mass    .75                
## 3 birth_year    .16  .15</code></pre>
<p>Incidentally, if you are generating a report from R Markdown and want your tables to be nicely formatted you can use <code><a href="https://rdrr.io/pkg/knitr/man/kable.html">knitr::kable()</a></code>.</p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">starwars</span> <span class="op">%&gt;%</span>
  <span class="fu">select</span><span class="op">(</span><span class="va">height</span>, <span class="va">mass</span>, <span class="va">birth_year</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/correlate.html">correlate</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"spearman"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/shave.html">shave</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://corrr.tidymodels.org/reference/fashion.html">fashion</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">term</th>
<th align="left">height</th>
<th align="left">mass</th>
<th align="left">birth_year</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">height</td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">mass</td>
<td align="left">.75</td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">birth_year</td>
<td align="left">.16</td>
<td align="left">.15</td>
<td align="left"></td>
</tr>
</tbody>
</table></div>
</div>
<div id="simulating-bivariate-data" class="section level2">
<h2>
<span class="header-section-number">2.2</span> Simulating bivariate data<a class="anchor" aria-label="anchor" href="#simulating-bivariate-data"><i class="fas fa-link"></i></a>
</h2>
<p>You have already learned how to simulate data from the normal distribution using the function <code><a href="https://rdrr.io/r/stats/Normal.html">rnorm()</a></code>. Recall that <code><a href="https://rdrr.io/r/stats/Normal.html">rnorm()</a></code> allows you to specify the mean and standard deviation of a single variable. How do we simulate correlated variables?</p>
<p>It should be clear that you can't just run <code><a href="https://rdrr.io/r/stats/Normal.html">rnorm()</a></code> twice and combine the variables, because then you end up with two variables that are unrelated, i.e., with a correlation of zero.</p>
<p>The package <strong><code>MASS</code></strong> provides a function <code>mvrnorm()</code> which is the 'multivariate' version of rnorm (hence the function name, <code>mv</code> + <code>rnorm</code>, which makes it easy to remember.</p>
<div class="watchout">
<p>
The <strong><code>MASS</code></strong> package comes pre-installed with R. But the only function you'll probably ever want to use from <strong><code>MASS</code></strong> is <code>mvrnorm()</code>, so rather than load in the package using <code><a href="http://www.stats.ox.ac.uk/pub/MASS4/">library("MASS")</a></code>, it is preferable to use <code><a href="https://rdrr.io/pkg/MASS/man/mvrnorm.html">MASS::mvrnorm()</a></code>, especially as <strong><code>MASS</code></strong> and the <strong><code>dplyr</code></strong> package from <strong><code>tidyverse</code></strong> don't play well together, due to both packages having the function <code>select()</code>. So if you load in <strong><code>MASS</code></strong> after you load in <strong><code>tidyverse</code></strong>, you'll end up getting the <strong><code>MASS</code></strong> version of <code>select()</code> instead of the <strong><code>dplyr</code></strong> version. It will do your head in trying to figure out what is wrong with your code, so always use <code><a href="https://rdrr.io/pkg/MASS/man/mvrnorm.html">MASS::mvrnorm()</a></code> without loading <code><a href="http://www.stats.ox.ac.uk/pub/MASS4/">library("MASS")</a></code>.
</p>
<blockquote class="twitter-tweet">
<p lang="en" dir="ltr">
MASS before dplyr, clashes not dire;<br>dplyr before MASS, pain in the ass. <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="http://t.co/vHIbGwSKd8">pic.twitter.com/vHIbGwSKd8</a>
</p>
— Dale Barr (<span class="citation">(<span class="citeproc-not-found" data-reference-id="dalejbarr"><strong>???</strong></span>)</span>) <a href="https://twitter.com/dalejbarr/status/516986671129452544?ref_src=twsrc%5Etfw">September 30, 2014</a>
</blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>
<p>Have a look at the documentation for the <code>mvrnorm()</code> function (type <code><a href="https://rdrr.io/pkg/MASS/man/mvrnorm.html">?MASS::mvrnorm</a></code> in the console).</p>
<p>There are three arguments to take note of:</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="6%">
<col width="93%">
</colgroup>
<thead><tr class="header">
<th align="left">arg</th>
<th align="left">description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">n</td>
<td align="left">the number of samples required</td>
</tr>
<tr class="even">
<td align="left">mu</td>
<td align="left">a vector giving the means of the variables</td>
</tr>
<tr class="odd">
<td align="left">Sigma</td>
<td align="left">a positive-definite symmetric matrix specifying the covariance matrix of the variables.</td>
</tr>
</tbody>
</table></div>
<p>The descriptions for <code>n</code> and <code>mu</code> are understandable, but what is a "positive-definite symmetric matrix specifying the covariance"?</p>
<p>When you have multivariate data, the <strong>covariance matrix</strong> (also known as the <strong>variance-covariance</strong> matrix) specifies the variances of the individual variables and their interrelationships. It is like a multidimensional version of the <strong>standard deviation</strong>. To fully describe a univariate normal distribution, you need to know only the mean and standard deviation; to describe a bivariate normal distribution, you need the means of each of the two variables, their standard deviations, and their correlation; for a multivariate distribution with more the two variables you need the means for all of the variables, their standard deviations, and all of the possible pairwise correlations. <strong>These concepts become very important once we start talking about mixed-effects modelling.</strong></p>
<p>You can think of a covariance matrix as something like the correlation matrix that you saw above; indeed, with a few calculations you can turn a covariance matrix into a correlation matrix.</p>
<div class="info">
<p>What's all this talk about the Matrix? Wasn't that a sci-fi film series from the 1990s?</p>
<p>In mathematics, matrices are just generalizations of the concept of a vector: a vector can be thought of as having one dimension, whereas a matrix can have any number of dimensions.</p>
<p>So the matrix</p>
<p><span class="math display">\[
\begin{pmatrix}
1 &amp; 4 &amp; 7 \\
2 &amp; 5 &amp; 8 \\
3 &amp; 6 &amp; 9 \\
\end{pmatrix}
\]</span></p>
<p>is a 3 (row) by 3 (column) matrix containing the column vectors <span class="math inline">\(\begin{pmatrix} 1 \\ 2 \\ 3 \\ \end{pmatrix}\)</span>, <span class="math inline">\(\begin{pmatrix} 4 \\ 5 \\ 6 \\ \end{pmatrix}\)</span>, and <span class="math inline">\(\begin{pmatrix} 7 \\ 8 \\ 9 \\ \end{pmatrix}\)</span>. Conventionally, we refer to matrices in <span class="math inline">\(i\)</span> by <span class="math inline">\(j\)</span> format, with <span class="math inline">\(i\)</span> being the number of rows and <span class="math inline">\(j\)</span> being the number of columns. So a 3x2 matrix has 3 rows and 2 columns, like so.</p>
<p><span class="math display">\[
\begin{pmatrix}
a &amp; d \\
b &amp; e \\
c &amp; f \\
\end{pmatrix}
\]</span></p>
<p>A <strong>square matrix</strong> is a matrix where the number of rows is equal to the number of columns.</p>
<p>You can create the above matrix in R using the <code><a href="https://rdrr.io/r/base/matrix.html">matrix()</a></code> function (see below) or by binding together vectors using the base R <code><a href="https://rdrr.io/r/base/cbind.html">cbind()</a></code> and <code><a href="https://rdrr.io/r/base/cbind.html">rbind()</a></code>, which bind vectors together column-wise and row-wise, respectively. Try <code><a href="https://rdrr.io/r/base/cbind.html">cbind(1:3, 4:6, 7:9)</a></code> in your console.</p>
</div>
<p>Now what is all this about the matrix being "positive-definite" and "symmetric"? These are mathematical requirements about the kinds of matrices that can represent possible multivariate normal distributions. In other words, the covariance matrix you supply must be represent a legal multivariate normal distribution. At this point, you don't really need to know much more about this than that.</p>
<iframe src="https://dalejbarr.github.io/bivariate/index.html" width="420" height="620" style="border: none;">
</iframe>
<p>Let's start by simulating data representing hypothetical humans and their heights and weights. We know these things are correlated. What we need to be able to simulate data are means and standard deviations for these two variables and their correlation.</p>
<p>I found some data <a href="https://www.geogebra.org/m/RRprACv4">here</a> which I converted into a CSV file. If you want to follow along, download the file <a href="data/heights_and_weights.csv" download="heights_and_weights.csv">heights_and_weights.csv</a>. Here's how the scatterplot looks:</p>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">handw</span> <span class="op">&lt;-</span> <span class="fu">read_csv</span><span class="op">(</span><span class="st">"data/heights_and_weights.csv"</span>, col_types <span class="op">=</span> <span class="st">"dd"</span><span class="op">)</span>

<span class="fu">ggplot</span><span class="op">(</span><span class="va">handw</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">height_in</span>, <span class="va">weight_lbs</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_point</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">.2</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"height (inches)"</span>, y <span class="op">=</span> <span class="st">"weight (pounds)"</span><span class="op">)</span> </code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:heights-and-weights"></span>
<img src="02-bivariate-simulation_files/figure-html/heights-and-weights-1.png" alt="Heights and weights of 475 humans (including infants)" width="100%"><p class="caption">
Figure 2.5: Heights and weights of 475 humans (including infants)
</p>
</div>
<p>Now, that's not quite a linear relationship. We can make it into one by log transforming each of the variables first.</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">handw_log</span> <span class="op">&lt;-</span> <span class="va">handw</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>hlog <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">height_in</span><span class="op">)</span>,
         wlog <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">weight_lbs</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:handw-log"></span>
<img src="02-bivariate-simulation_files/figure-html/handw-log-1.png" alt="Log transformed heights and weights." width="100%"><p class="caption">
Figure 2.6: Log transformed heights and weights.
</p>
</div>
<p>The fact that there is a big cluster of points in the top right tail of the cloud probably indicates that there were more adults than kids in this sample, since adults are taller and heavier.</p>
<p>The mean log height is 4.11 (SD = 0.26), while the mean log weight is 4.74 (SD = 0.65). The correlation between log height and log weight, which we can get using the <code><a href="https://rdrr.io/r/stats/cor.html">cor()</a></code> function, is very high, 0.96.</p>
<p>We now have all the information we need to simulate the heights and weights of, let's say, 500 humans. But how do we get this information into <code><a href="https://rdrr.io/pkg/MASS/man/mvrnorm.html">MASS::mvrnorm()</a></code>? We know the first part of the function call will be <code><a href="https://rdrr.io/pkg/MASS/man/mvrnorm.html">MASS::mvrnorm(500, c(4.11, 4.74), ...)</a></code>, but what about <code>Sigma</code>, the covariance matrix? We know from above that <span class="math inline">\(\hat{\sigma}_x = 0.26\)</span> and <span class="math inline">\(\hat{\sigma}_y = 0.65\)</span>, and <span class="math inline">\(\hat{\rho}_{xy} = 0.96\)</span>.</p>
<p>A covariance matrix representating <code>Sigma</code> (<span class="math inline">\(\mathbf{\Sigma}\)</span>) for bivariate data has the following format:</p>
<p><span class="math display">\[
\mathbf{\Sigma} =
\begin{pmatrix}
{\sigma_x}^2                &amp; \rho_{xy} \sigma_x \sigma_y \\
\rho_{yx} \sigma_y \sigma_x &amp; {\sigma_y}^2 \\
\end{pmatrix}
\]</span></p>
<p>The variances (squared standard deviations, <span class="math inline">\({\sigma_x}^2\)</span> and <span class="math inline">\({\sigma_y}^2\)</span>) are in the diagonal, and the covariances (the correlation times the two standard deviations, <span class="math inline">\(\rho_{xy} \sigma_x \sigma_y\)</span>) are in the off-diagonal. It is useful to remember that the covariance is just the correlation times the product of the two standard deviations. As we saw above with the correlation matrices, there is redundant information in the table; namely, the covariance appears in the top right cell as well as the bottom left cell of the matrix.</p>
<p>So plugging in the values we got above, our covariance matrix should be</p>
<p><span class="math display">\[
\begin{pmatrix}
.26^2 &amp; (.96)(.26)(.65) \\
(.96)(.65)(.26) &amp; .65^2 \\
\end{pmatrix} =
\begin{pmatrix}
.067 &amp; .162 \\
.162 &amp; .423 \\
\end{pmatrix}
\]</span></p>
<p>OK, how do we form <code>Sigma</code> in R so that we can pass it to the <code>mvrnorm()</code> function? We will use the <code><a href="https://rdrr.io/r/base/matrix.html">matrix()</a></code> function, as shown below.</p>
<p>First let's define our covariance and store it in the variable <code>my_cov</code>.</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">my_cov</span> <span class="op">&lt;-</span> <span class="fl">.96</span> <span class="op">*</span> <span class="fl">.26</span> <span class="op">*</span> <span class="fl">.65</span></code></pre></div>
<p>Now we'll use <code><a href="https://rdrr.io/r/base/matrix.html">matrix()</a></code> to define our <code>Sigma</code>, <code>my_Sigma</code>.</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">my_Sigma</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">.26</span><span class="op">^</span><span class="fl">2</span>, <span class="va">my_cov</span>, <span class="va">my_cov</span>, <span class="fl">.65</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span>, ncol <span class="op">=</span> <span class="fl">2</span><span class="op">)</span>
<span class="va">my_Sigma</span></code></pre></div>
<pre><code>##         [,1]    [,2]
## [1,] 0.06760 0.16224
## [2,] 0.16224 0.42250</code></pre>
<div class="info">
<p>
Confused about the <code><a href="https://rdrr.io/r/base/matrix.html">matrix()</a></code> function?
</p>
<p>
The first argument is a vector of values, which we created above using <code><a href="https://rdrr.io/r/base/c.html">c()</a></code>. The <code>ncol</code> argument specifies how many columns the matrix should have. There is also an <code>nrow</code> argument that you could use, but if you give it one of the dimensions, it can infer the size of the other using the length of the vector supplied as the first argument.
</p>
<p>
You can see that <code><a href="https://rdrr.io/r/base/matrix.html">matrix()</a></code> fills in the elements of the matrix column by column, rather than row by row by running the following code:
</p>
<p>
<code><a href="https://rdrr.io/r/base/matrix.html">matrix(c("a", "b", "c", "d"), ncol = 2)</a></code>
</p>
<p>
If you want to change this behavior, set the <code>byrow</code> argument to <code>TRUE</code>.
</p>
<p>
<code><a href="https://rdrr.io/r/base/matrix.html">matrix(c("a", "b", "c", "d"), ncol = 2, byrow = TRUE)</a></code>
</p>
</div>
<p>Great. Now that we've got <code>my_Sigma</code>, we're ready to use <code><a href="https://rdrr.io/pkg/MASS/man/mvrnorm.html">MASS::mvrnorm()</a></code>. Let's test it out by creating 6 synthetic humans.</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">62</span><span class="op">)</span> <span class="co"># for reproducibility</span>

<span class="co"># passing the *named* vector c(height = 4.11, weight = 4.74)</span>
<span class="co"># for mu gives us column names in the output</span>
<span class="va">log_ht_wt</span> <span class="op">&lt;-</span> <span class="fu">MASS</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/MASS/man/mvrnorm.html">mvrnorm</a></span><span class="op">(</span><span class="fl">6</span>, 
                           <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>height <span class="op">=</span> <span class="fl">4.11</span>, weight <span class="op">=</span> <span class="fl">4.74</span><span class="op">)</span>, 
                           <span class="va">my_Sigma</span><span class="op">)</span>

<span class="va">log_ht_wt</span></code></pre></div>
<pre><code>##        height   weight
## [1,] 4.254209 5.282913
## [2,] 4.257828 4.895222
## [3,] 3.722376 3.759767
## [4,] 4.191287 4.764229
## [5,] 4.739967 6.185191
## [6,] 4.058105 4.806485</code></pre>
<p>So <code><a href="https://rdrr.io/pkg/MASS/man/mvrnorm.html">MASS::mvrnorm()</a></code> returns a matrix with a row for each simulated human, with the first column representing the log height and the second column representing the log weight. But log heights and log weights are not very useful to us, so let's transform them back by using <code><a href="https://rdrr.io/r/base/Log.html">exp()</a></code>, which is the inverse of the <code><a href="https://rdrr.io/r/base/Log.html">log()</a></code> transform.</p>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="va">log_ht_wt</span><span class="op">)</span></code></pre></div>
<pre><code>##         height    weight
## [1,]  70.40108 196.94276
## [2,]  70.65632 133.64963
## [3,]  41.36254  42.93844
## [4,]  66.10779 117.24065
## [5,] 114.43045 485.50576
## [6,]  57.86453 122.30092</code></pre>
<p>So our first simulated human is 70.4 inches tall (about 5'5" or X) and weighs 196.94 pounds (89.32 kg). Sounds about right! (Note also that it will generate observations outside of our original data; we'll get super tall humans, like observation 5, but at least the weight/height relationship will be preserved.)</p>
<p>OK, let's randomly generate a bunch of humans, transform them from log to inches and pounds, and plot them against our original data to see how we're doing.</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## simulate new humans</span>
<span class="va">new_humans</span> <span class="op">&lt;-</span> <span class="fu">MASS</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/MASS/man/mvrnorm.html">mvrnorm</a></span><span class="op">(</span><span class="fl">500</span>, 
                            <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>height_in <span class="op">=</span> <span class="fl">4.11</span>, weight_lbs <span class="op">=</span> <span class="fl">4.74</span><span class="op">)</span>,
                            <span class="va">my_Sigma</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="co"># back-transform from log to inches and pounds</span>
  <span class="fu">as_tibble</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="co"># make tibble for plotting</span>
  <span class="fu">mutate</span><span class="op">(</span>type <span class="op">=</span> <span class="st">"simulated"</span><span class="op">)</span> <span class="co"># tag them as simulated</span>

<span class="co">## combine real and simulated datasets</span>
<span class="co">## handw is variable containing data from heights_and_weights.csv</span>
<span class="va">alldata</span> <span class="op">&lt;-</span> <span class="fu">bind_rows</span><span class="op">(</span><span class="va">handw</span> <span class="op">%&gt;%</span> <span class="fu">mutate</span><span class="op">(</span>type <span class="op">=</span> <span class="st">"real"</span><span class="op">)</span>, 
                     <span class="va">new_humans</span><span class="op">)</span>

<span class="fu">ggplot</span><span class="op">(</span><span class="va">alldata</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">height_in</span>, <span class="va">weight_lbs</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>colour <span class="op">=</span> <span class="va">type</span><span class="op">)</span>, alpha <span class="op">=</span> <span class="fl">.1</span><span class="op">)</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:plot-together"></span>
<img src="02-bivariate-simulation_files/figure-html/plot-together-1.png" alt="Real and simulated humans." width="100%"><p class="caption">
Figure 2.7: Real and simulated humans.
</p>
</div>
<p>You can see that our simulated humans are much like the normal ones, except that we are creating humans outside the normal range of heights and weights.</p>
</div>
<div id="relationship-between-correlation-and-regression" class="section level2">
<h2>
<span class="header-section-number">2.3</span> Relationship between correlation and regression<a class="anchor" aria-label="anchor" href="#relationship-between-correlation-and-regression"><i class="fas fa-link"></i></a>
</h2>
<p>OK, we know how to estimate correlations, but what if we wanted to predict the weight of someone given their height? This might sound like an impractical problem, but in fact, <a href="https://link.springer.com/article/10.1186/s12245-018-0212-9">emergency medical technicians can use this technique to get a quick estimate of people's weights in emergency situations</a> where they need to administer drugs or procedures whose safety depends on the patient's weight, and don't have time to weigh them.</p>
<p>Recall that the GLM for a simple regression model is</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1 X_i + e_i.\]</span></p>
<p>Here, we are trying to predict the weight (<span class="math inline">\(Y_i\)</span>) of person <span class="math inline">\(i\)</span> from their observed height (<span class="math inline">\(X_i\)</span>). In this equation, <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are the y-intercept and slope parameters respectively, and the <span class="math inline">\(e_i\)</span>s are the residuals. It is conventionally assumed that the <span class="math inline">\(e_i\)</span> values are from a normal distribution with mean of zero and variance <span class="math inline">\(\sigma^2\)</span>; the math-y way of saying this is <span class="math inline">\(e_i \sim N(0, \sigma^2)\)</span>, where <span class="math inline">\(\sim\)</span> is read as "distributed according to" and <span class="math inline">\(N(0, \sigma^2)\)</span> means "Normal distribution (<span class="math inline">\(N\)</span>) with mean of 0 and variance of <span class="math inline">\(\sigma^2\)</span>".</p>
<p>It turns out that if we have estimates of the means of X and Y (denoted by <span class="math inline">\(\mu_x\)</span> and <span class="math inline">\(\mu_y\)</span> respectively), of their standard deviations (<span class="math inline">\(\hat{\sigma}_x\)</span> and <span class="math inline">\(\hat{\sigma}_y\)</span>), and the correlation between X and Y (<span class="math inline">\(\hat{\rho}\)</span>), we have all the information we need to estimate the parameters of the regression equation <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. Here's how.</p>
<p>First, the slope of the regression line <span class="math inline">\(\beta_1\)</span> equals the correlation coefficient <span class="math inline">\(\rho\)</span> times the ratio of the standard deviations of <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span>.</p>
<p><span class="math display">\[\beta_1 = \rho \frac{\sigma_Y}{\sigma_X}\]</span></p>
<p>Given the estimates above for log height and weight, can you solve for <span class="math inline">\(\beta_1\)</span>?</p>
<!-- TODO make this use webex -->
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">b1</span> <span class="op">&lt;-</span> <span class="fl">.96</span> <span class="op">*</span> <span class="op">(</span><span class="fl">.65</span> <span class="op">/</span> <span class="fl">.26</span><span class="op">)</span>
<span class="va">b1</span></code></pre></div>
<pre><code>## [1] 2.4</code></pre>
<p>The next thing to note is that for mathematical reasons, the regression line is guaranteed to go through the point corresponding to the mean of <span class="math inline">\(X\)</span> and the mean of <span class="math inline">\(Y\)</span>, i.e., the point <span class="math inline">\((\mu_x, \mu_y)\)</span>. (You can think of the regression line "pivoting" around that point depending on the slope). You also know that <span class="math inline">\(\beta_0\)</span> is the y-intercept, the point where the line crosses the vertical axis at <span class="math inline">\(X = 0\)</span>. From this information, and the estimates above, can you figure out the value of <span class="math inline">\(\beta_0\)</span>?</p>
<!-- TODO: use webex -->
<p>Here is the reasoning by which you can solve for <span class="math inline">\(\beta_0\)</span>.</p>
<p>The <span class="math inline">\(\beta_1\)</span> value tells you that for each change in <span class="math inline">\(X\)</span> you have a corresponding change of 2.4 for <span class="math inline">\(Y\)</span>, and you know that the line goes through the points <span class="math inline">\((\mu_x, \mu_y)\)</span> as well as the y-intercept <span class="math inline">\((0, \beta_0)\)</span>.</p>
<p>Think about stepping back unit-by-unit from <span class="math inline">\(X = \mu_x\)</span> to <span class="math inline">\(X = 0\)</span>.
At <span class="math inline">\(X = \mu_x\)</span>, <span class="math inline">\(Y = 4.74\)</span>. Each unit step you take backward in the X dimension, <span class="math inline">\(Y\)</span> will drop by <span class="math inline">\(\beta_1 = 2.4\)</span> units. When you get to zero, <span class="math inline">\(Y\)</span> will have dropped from <span class="math inline">\(\mu_y\)</span> to <span class="math inline">\(\mu_y - \mu_x\beta_1\)</span>.</p>
<p>So the general solution is: <span class="math inline">\(\beta_0 = \mu_y - \mu_x\beta_1\)</span>.</p>
<p>Since <span class="math inline">\(\beta_1 = 2.4\)</span>, <span class="math inline">\(\mu_x = 4.11\)</span>, and <span class="math inline">\(\mu_y = 4.74\)</span>, <span class="math inline">\(\beta_0 = -5.124\)</span>. Thus, our regression equation is:</p>
<p><span class="math display">\[Y_i =  -5.124 + 2.4X_i + e_i.\]</span></p>
<p>To check our results, let's first run a regression on the log-transformed data using <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>, which estimates parameters using ordinary least squares regression.</p>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wlog</span> <span class="op">~</span> <span class="va">hlog</span>, <span class="va">handw_log</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wlog ~ hlog, data = handw_log)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.63296 -0.09915 -0.01366  0.09285  0.65635 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -5.26977    0.13169  -40.02   &lt;2e-16 ***
## hlog         2.43304    0.03194   76.17   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.1774 on 473 degrees of freedom
## Multiple R-squared:  0.9246, Adjusted R-squared:  0.9245 
## F-statistic:  5802 on 1 and 473 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Looks pretty close. The reason that it doesn't match exactly is only because we've rounded off our estimates to two decimal places for convenience.</p>
<p>As another check, let's superimpose the regression line we computed by hand on the scatterplot of the log-transformed data.</p>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="va">handw_log</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">hlog</span>, <span class="va">wlog</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">.2</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"log(height)"</span>, y <span class="op">=</span> <span class="st">"log(weight)"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_abline</span><span class="op">(</span>intercept <span class="op">=</span> <span class="op">-</span><span class="fl">5.124</span>, slope <span class="op">=</span> <span class="fl">2.4</span>, colour <span class="op">=</span> <span class="st">'blue'</span><span class="op">)</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:scatter-with-line"></span>
<img src="02-bivariate-simulation_files/figure-html/scatter-with-line-1.png" alt="Log transformed values with superimposed regression line." width="100%"><p class="caption">
Figure 2.8: Log transformed values with superimposed regression line.
</p>
</div>
<p>Looks right.</p>
<p>To close, here are a few implications from the relationship between correlation and regression.</p>
<ul>
<li>
<span class="math inline">\(\beta_1 = 0\)</span> is the same as <span class="math inline">\(\rho = 0\)</span>.</li>
<li>
<span class="math inline">\(\beta_1 &gt; 0\)</span> implies <span class="math inline">\(\rho &gt; 0\)</span>, since standard deviations can't be negative.</li>
<li>
<span class="math inline">\(\beta_1 &lt; 0\)</span> implies <span class="math inline">\(\rho &lt; 0\)</span>, for the same reason.</li>
<li>Rejecting the null hypothesis that <span class="math inline">\(\beta_1 = 0\)</span> is the same as rejecting the null hypothesis that <span class="math inline">\(\rho = 0\)</span>. The p-values that you get for <span class="math inline">\(\beta_1\)</span> in <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> will be the same as the one you get for <span class="math inline">\(\rho\)</span> from <code><a href="https://rdrr.io/r/stats/cor.test.html">cor.test()</a></code>.</li>
</ul>
</div>
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  if (t = document.getElementById("webex-total_correct")) {
    t.innerHTML =
      document.getElementsByClassName("webex-correct").length + " of " +
      document.getElementsByClassName("webex-solveme").length + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

window.onload = function() {
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }

  update_total_correct();
}

</script><script>
$( document ).ready(function() {
  var cite = ' ';
  var psyteachr = ' <a href="https://psyteachr.github.io/"><img src="images/logos/psyteachr_logo.png" style="height: 31px; color: white;" alt="psyTeachR: Reproducible Research" /></a>';
  var license = ' <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" target="blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>';

  $("footer div.row div:eq(1) p").html(
    psyteachr + license + cite
  );
});
</script><div class="chapter-nav">
<div class="prev"><a href="introduction.html"><span class="header-section-number">1</span> Introduction</a></div>
<div class="next"><a href="multiple-regression.html"><span class="header-section-number">3</span> Multiple regression</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#understanding-correlation-and-regression-through-bivariate-simulation"><span class="header-section-number">2</span> Understanding correlation and regression through bivariate simulation</a></li>
<li><a class="nav-link" href="#correlation-matrices"><span class="header-section-number">2.1</span> Correlation matrices</a></li>
<li><a class="nav-link" href="#simulating-bivariate-data"><span class="header-section-number">2.2</span> Simulating bivariate data</a></li>
<li><a class="nav-link" href="#relationship-between-correlation-and-regression"><span class="header-section-number">2.3</span> Relationship between correlation and regression</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/psyteachr/stat-models-v1/blob/master/02-bivariate-simulation.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/psyteachr/stat-models-v1/edit/master/02-bivariate-simulation.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Learning Statistical Models Through Simulation in R</strong>" was written by Dale J. Barr. It was last built on 2021-10-08.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
